// NgApp-WOT/src/app/part/part.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-part',
  templateUrl: './part.component.html',
  styleUrls: ['./part.component.css']
})
export class PartComponent implements OnInit {

  partFilePath = "https://localhost:44359/PartFiles/";
  
  parts: Array<any>;

  apiResponse = '';  
  responseColor = '';
  responseClass = '';

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
     this.loadParts();  
  }

  loadParts(){
    this.dataService.getAllParts()
      .subscribe(
        data => {          
          console.log(data);

          data.map((part, i) => {
            part.partFilePath = this.partFilePath+''+part.partFile;
          });


          this.parts = data;
          this.responseColor = 'green';
          this.apiResponse = 'Success!';
          this.responseClass = 'successResponse';

          console.log(this.parts);
        },
        error => {
          console.log(error);
          if (error.status == 401)            
            this.apiResponse = 'Un-Authorized !';
          else
            this.apiResponse = 'Error !';
          
          this.responseColor = 'red';
          this.responseClass = 'errorResponse';
          this.parts = [];      
      });
  }

  editPart(part) {
    this.router.navigate(['/part-edit/'+ part.partId]);
  }

  removePart(part) {
    this.router.navigate(['/part-remove/'+ part.partId]);
  }

  createPart() {
    setTimeout(() => {
      this.router.navigate(['/part-create']);
    }, 500);
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header componentHeader" >
                    <h4>
                        Parts
                        <p></p>
                        <span *ngIf="responseColor=='red'"
                            [class]="responseClass" >
                            {{apiResponse}}
                        </span>                        
                    </h4>

                    <p></p>
                    <div>
                        <button 
                            type="button" 
                            (click)="createPart()" 
                            class="btn btn-success">
                                Create New Part
                        </button>
                    </div>
                </div>
                <div class="card-body">  
                    <div
                        *ngIf="parts?.length>0; else noParts"
                        class="container">

                        <div class="form-group">
                            <input type="text" 
                                class="searchControl form-control" 
                                placeholder="Search Part" [(ngModel)]="term">
                        </div>
                        <p></p>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Desc</th>
                                    <th>Qty</th>
                                    <th>File</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let p of parts  | filter:term | paginate
                                        : {
                                            itemsPerPage: tableSize,
                                            currentPage: page,
                                            totalItems: count
                                        };
                                        let i = index
                                    ">
                                    <th scope="row">{{ p.partId }}</th>
                                    <td>{{ p.name }}</td>
                                    <td>
                                        <span *ngIf="p.desc!=null && p.desc.length>10; else fullDesc">
                                            {{p.desc.substring(0,10)}}...
                                        </span>
                                        <ng-template #fullDesc>
                                            {{p.desc}}
                                        </ng-template>
                                    </td>
                                    <td>{{ p.qty }}</td>
                                    <td>
                                        <span *ngIf="p.partFile!='N/A'; else noImage">
                                            <img width="35" height="35" [src]="p.partFilePath" alt="N/A" />
                                        </span>
                                        <ng-template #noImage>
                                            N/A
                                        </ng-template>
                                    </td>
                                    <td>
                                        <div class="row">
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" (click)="editPart(p)" class="btn btn-primary">
                                                    <i class="bi bi-pencil-square"></i>
                                                </button>
                                            </div>
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" (click)="removePart(p)" class="btn btn-danger">
                                                    <i class="bi bi-trash"></i>
                                                </button>
                                            </div>
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" (click)="uploadPart(p)" class="btn btn-success">
                                                    <i class='bi bi-upload'></i>
                                                </button>
                        
                                            </div>
                                            <div class="col-6"></div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                            <pagination-controls previousLabel="Prev" nextLabel="Next" (pageChange)="onTableDataChange($event)">
                            </pagination-controls>
                        </div>
                    </div>
                    <ng-template #noParts>
                        <div class="container">
                            <span class="noParts">
                                Parts Not Found !
                            </span>                            
                        </div>
                    </ng-template>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Part/Part.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AuthService from "../../services/auth.service";
import PartService from "../../services/part.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Button from "react-bootstrap/Button";

const Part = () => {
  let navigate = useNavigate();

  const partFilePath = "https://localhost:44359/PartFiles/";

  const [parts, setParts] = useState([]);

  const getAllParts = () => {
    PartService.allParts()
      .then((response) => {
        setParts(response.data);
        // setParts([]);

        // console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          navigate("/login");
        }
      });
  };

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getAllParts();
  }, []);

  const displayImage = (cell) => {
    var imagePath = partFilePath + cell;
    if (cell === "N/A") return <div className="noImage">N/A</div>;
    else return <img src={imagePath} width="70" height="80" />;
  };
  const displayQty = (cell) => {
    return <div className="qtyColumn">{cell}</div>;
  };
  const displayActionBtn = (cell, row) => {
    // console.log(row);
    return (
      <div>
        {" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editPart(e, row.partId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>{" "}
        <Button
          className="btn btn-danger"
          type="button"
          onClick={(e) => removePart(e, row.partId)}
        >
          <i className="bi bi-trash"></i>
        </Button>{" "}
        <Button
          className="btn btn-success"
          type="button"
          onClick={(e) => fileUpload(e, row.partId)}
        >
          <i className="bi bi-upload"></i>
        </Button>
      </div>
    );
  };
  const displayDesc = (cell) => {
    // cell = null;
    // cell = "";
    if (cell === null || cell === "") return "N/A";
    else {
      if (cell.length > 30) return cell.substring(0, 30) + " ...MORE";
      else return cell;
    }
  };

  const columns = [
    {
      dataField: "partId",
      text: "#",
      sort: true,
      style: { width: "80" },
    },
    {
      dataField: "name",
      text: "Name",
      sort: true,
      // filter: textFilter(),
    },
    {
      dataField: "desc",
      text: "Desc",
      formatter: (cell) => displayDesc(cell),
    },
    {
      dataField: "qty",
      text: "Qty",
      formatter: (cell) => displayQty(cell),
    },
    {
      dataField: "partFile",
      text: "File",
      formatter: (cell) => displayImage(cell),
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const createNewPart = () => {
    navigate("/part-create");
  };

  const editPart = (e, partId) => {
    console.log("edit part : ", partId);
    navigate("/part-edit/" + partId);
  };
  const removePart = (e, partId) => {
    console.log("remove part : ", partId);
    navigate("/part-remove/" + partId);
  };
  const fileUpload = (e, partId) => {
    console.log("file upload : ", partId);
    navigate("/part-file-upload/" + partId);
  };

  return (
    <div className="container">
      <div className="mainHeader">Parts</div>
      <hr />
      <Button
        className="btn btn-success"
        type="button"
        onClick={(e) => createNewPart(e)}
      >
        Create New Part
      </Button>
      <p></p>
      {parts && parts.length > 0 ? (
        <BootstrapTable
          bootstrap4
          keyField="partId"
          data={parts}
          columns={columns}
          pagination={paginationFactory({ sizePerPage: 5 })}
          filter={filterFactory()}
        />
      ) : (
        <div className="noParts">No Parts!</div>
      )}
    </div>
  );
};

export default Part;
