// NgApp-WOT/src/app/xfer-parts/xfer-parts.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-xfer-parts',
  templateUrl: './xfer-parts.component.html',
  styleUrls: ['./xfer-parts.component.css']
})
export class XferPartsComponent implements OnInit {

  opId: string;
  woId: number;

  xferInfo: {
    customerName: '',
    customerOrderId: 0,
    customerOrderQTY: 0,
    operationNumber: 0,
    workOrderId: 0,
  };
  parts: [{ text: '', value: ''}];

  xferForm: FormGroup;
  submitted = false;
  xferModel = {
    operationId: 0,
    partId:0, 
    xFERQTY: 0,
  };


  apiResponse = '';  
  responseColor = '';
  modelErrors = [];
  
  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {

    this.woId = this.localDataService.getWorkOrderId();
    if (this.woId===null || isNaN(+this.woId)) {
      console.log('Invalid Work-Order!');
      this.router.navigate(['/work-order']);
    }

    this.opId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.opId)) {
      console.log('Not a Number!');
      this.router.navigate(['/work-order']);
    }
    else {

      this.xferForm = this.fb.group({      
        PartId: ['', [Validators.required]],  
        XFERQTY: ['', [Validators.pattern("^[0-9]*$")]], 
      });   
    
      this.getParts();
      this.getOperationDetails(Number(this.opId));
    }
  }

  getParts() {
    this.dataService.getPartList()
        .subscribe(
          data => {           
            console.log(data);
            this.parts = data;
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
  }

  getOperationDetails(opId) {
    this.dataService.getOperationDetails(opId)
        .subscribe(
          data => {           
            console.log(data);
            this.xferInfo = data;
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
  }

  
  goBack() {
    this.router.navigate(['/operation/'+this.woId]);
  }

  checkForNumbersOnly(newVal) {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal))
      // console.log('ok');
      return true;
    else
      // console.log('Only Numbers Allowed !!!');
      return false;
  }

  get xferFormControl() {
    return this.xferForm.controls;
  }

  onSubmit(): void {
    this.submitted = true;

    if (this.xferForm.value["PartId"]==='' ||  this.xferForm.value["PartId"]===null) {
      console.log('form in-valid!');
      return;
    }  
      
    if (!this.checkForNumbersOnly(this.xferForm.value["XFERQTY"])) {      
      console.log('form in-valid!');
      return;
    } 

    if (this.xferForm.value["XFERQTY"] === '')
      this.xferModel.xFERQTY = 0;
    else
      this.xferModel.xFERQTY = this.xferForm.value["XFERQTY"];        
      
 
    this.xferModel.operationId = Number(this.opId);
    this.xferModel.partId = this.xferForm.value["PartId"];        
        
    console.log(this.xferModel);  
    
    this.dataService.xferPartsForOperation(this.xferModel)
        .subscribe(
          response => {
            console.log(response);
            this.modelErrors = [];
            this.apiResponse = '';

            if (response.responseCode === 0) {              
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetXfer();
              this.submitted = false;
              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/operation/'+this.woId]);
              }, 2000);  
            }
            else {
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Customer-Order-Create');
            }
            else
              this.apiResponse = 'Error !';            
          }
        );
  }
  
  resetXfer(){
    this.xferForm.reset();
    this.submitted = false;
  }
}

<div class="container">
    <div class="col-md-8 mx-auto">
        <div class="card">
            <div class="card-header componentHeader">
                <div class="row">
                    <div class="col-md-10">
                        <h4>
                            <div>
                                XFER - Parts - TO - Operation
                                <br />
                                <div *ngIf="xferInfo" class="otherXferData">
                                    <h5>Customer : {{xferInfo.customerName}}
                                    </h5>
                                    <h5>Customer-Order # {{xferInfo.customerOrderId}}
                                    </h5>
                                    <h5>Customer-Order QTY # {{xferInfo.customerOrderQTY}}
                                    </h5>
                                    <h5>Work-Order # {{xferInfo.workOrderId}}
                                    </h5>
                                    <h5>Operation # {{opId}}
                                    </h5>
                                    <h5>Operation Number #&nbsp;
                                    {{localDataService.getOperationNumber(xferInfo.operationNumber)}}
                                    </h5>
                                </div>

                            </div>
                        </h4>
                        <h5 *ngIf="apiResponse">
                            <span [style.color]="responseColor">
                                {{apiResponse}}
                            </span>
                        </h5>
                        <h5 *ngIf="modelErrors.length > 0">
                            <ul [style.color]="responseColor">
                                <li *ngFor="let error of modelErrors">
                                    {{ error }}
                                </li>
                            </ul>
                        </h5>
                    </div>
                    <div class="col-md-2 ">
                        <button type="button" (click)="goBack()" class="btn btn-primary cancelBtn">
                            <i class="bi bi-arrow-return-left"></i> Back
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
        <form 
            class="form-xfer" 
            [formGroup]="xferForm" 
            (ngSubmit)="onSubmit()">
        
            <div class="row">
                <div class="col-md-2 mx-auto">                
                </div>
                <div class="col-md-8 mx-auto">   
                    <div class="form-group">
                        <label>Part</label>
                        <select class="form-control" 
                            formControlName="PartId">
                            <option value="">Choose Part</option>   
                            <option value={{p.value}} *ngFor="let p of parts">
                                {{p.text}}
                            </option>
                        </select>
                        <div class="alert alert-danger mt-2"
                            *ngIf="(xferFormControl.PartId.touched || submitted) && xferFormControl.PartId.errors?.required">
                            Part is required
                        </div>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <label>Qty-Required</label>
                        <input type="text" 
                            class="form-control qtyField" 
                            formControlName="XFERQTY" />
                        <div class="alert alert-danger mt-2"
                            *ngIf="(xferFormControl.XFERQTY.touched || submitted) && xferFormControl.XFERQTY.errors?.pattern">
                            Only Numbers are allowed
                        </div>
                    </div>
                </div>
                <div class="col-md-2 mx-auto">                
                </div>
             
            </div>
        
            <hr />
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success">
                            XFER Parts
                        </button>
                    </div>
                    <div class="col-sm-6">
                        <button type="button" 
                            (click)="resetXfer()" 
                            class="btn btn-primary cancelBtn">
                            Cancel
                        </button>
                    </div>
                </div>
            </div>
        </form>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Xfer_Parts_To_Op/Xfer_Parts.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import OperationService from "../../services/operation.service";
import { getOperationNumber } from "../../services/local.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Xfer_Parts = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [parts, setParts] = useState([]);
  const [xferInfo, setXferInfo] = useState({});

  const [modelErrors, setModelErrors] = useState([]);

  const [xferResponse, setXferResponse] = useState({});

  // form
  const [partId, setPartId] = useState("");
  const [xferQTY, setXferQTY] = useState(0);
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      getParts();
      getOperationDetails(id);
    }
  }, []);

  const getParts = () => {
    OperationService.getPartList()
      .then((response) => {
        setParts(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const getOperationDetails = (id) => {
    OperationService.getOperationDetails(id)
      .then((response) => {
        setXferInfo(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const findFormErrors = () => {
    const newErrors = {};

    if (!partId || partId === "") newErrors.partId = "Part is Required!";
    if (!xferQTY || xferQTY === "") newErrors.xferQTY = "XFER-QTY is Required!";
    else {
      if (!checkForNumbersOnly(xferQTY))
        newErrors.xferQTY = "Only Numbers are Allowed!";
    }

    return newErrors;
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      // for (let prop in error.response.data.errors) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var xferModel = {
        partId: partId,
        operationId: id,
        xFERQTY: parseInt(xferQTY),
      };
      console.log(xferModel);

      // api call
      OperationService.xferPartsForOperation(xferModel)
        .then((response) => {
          setModelErrors([]);
          setXferResponse({});
          console.log(response.data);

          var _xferResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setXferResponse(_xferResponse);

            setTimeout(() => {
              navigate("/operation/" + xferInfo.workOrderId);
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setXferResponse(_xferResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setXferResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setPartId("");
    setXferResponse({});
    setModelErrors([]);
  };

  const handlePartId = (event) => {
    setPartId(event.target.value);
    if (!errors[partId])
      setErrors({
        ...errors,
        partId: "",
      });
  };
  const handleXferQTY = (event) => {
    setXferQTY(event.target.value);
    if (!errors[xferQTY])
      setErrors({
        ...errors,
        xferQTY: "",
      });
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);
  const renderOptionsForParts = () => {
    return parts.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.text}>
          {dt.text}
        </option>
      );
    });
  };

  const goBack = (e) => {
    navigate("/operation/" + xferInfo.workOrderId);
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-10 mx-auto">
            <div className="card">
              <div className="card-header">
                <div className="row">
                  <div className="col-md-10 mx-auto">
                    <h3>XFER - Parts - TO - Operation</h3>
                    <div className="header">
                      <h5>Customer : {xferInfo.customerName}</h5>
                      <h5>Customer-Order # {xferInfo.customerOrderId}</h5>
                      <h5>Customer-Order QTY # {xferInfo.customerOrderQTY}</h5>
                      <h5>Work-Order # {xferInfo.workOrderId}</h5>
                      <h5>Operation # {id}</h5>
                      <h5>
                        Operation Number #{" "}
                        {getOperationNumber(xferInfo.operationNumber)}
                      </h5>
                    </div>
                    <p></p>{" "}
                    {xferResponse && xferResponse.responseCode === -1 ? (
                      <span className="xferError">
                        {xferResponse.responseMessage}
                      </span>
                    ) : (
                      <span className="xferSuccess">
                        {xferResponse.responseMessage}
                      </span>
                    )}
                    {modelErrors.length > 0 ? (
                      <div className="modelError">{modelErrorList}</div>
                    ) : (
                      <span></span>
                    )}
                  </div>
                  <div className="col-md-2 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="partId">
                        <Form.Label>Part</Form.Label>
                        <Form.Control
                          as="select"
                          value={partId}
                          isInvalid={!!errors.partId}
                          onChange={(e) => handlePartId(e)}
                        >
                          <option value="">Select Part</option>
                          {renderOptionsForParts()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.partId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="xferQTY">
                        <Form.Label>XFER QTY</Form.Label>
                        <Form.Control
                          className="qtyDisplay"
                          type="text"
                          isInvalid={!!errors.xferQTY}
                          onChange={(e) => handleXferQTY(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.xferQTY}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      XFER Parts
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Xfer_Parts;
