// NgApp-WOT/src/app/create-operator-log/create-operator-log.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LocalDataService } from '../services/local-data.service';
import { UserService } from '../services/user.service';
import { DataService } from '../services/data.service';

@Component({
  selector: 'app-create-operator-log',
  templateUrl: './create-operator-log.component.html',
  styleUrls: ['./create-operator-log.component.css']
})
export class CreateOperatorLogComponent implements OnInit {
  

  startRunTimeError = '';
  pauseRunTimeError = '';
  qtyDoneError = '';

  timeStartRunTime = { hour: 13, minute: 30 };
  timePauseRunTime = {hour: 13, minute: 30};
  meridian = true;    

  operationStatusCollection: Array<any>;
  workOrders: Array<any>;
  operations: Array<any>;
  opQtyData;

  oprLogForm: FormGroup;
  submitted = false;
  oprLogModel = {
    workOrderId: 0,
    operationId: 0,
    operationStatus: 0,
    opStartRunTime: undefined,
    opPauseRunTime: undefined,
    opQtyDone: 0,    
    userId: '',
    operatorId: 0,
  };

  apiResponse = '';  
  responseColor = '';
  modelErrors = [];

  constructor( private formBuilder: FormBuilder,
    public userService: UserService,
    public router: Router,
    public localDataService: LocalDataService,
    public dataService: DataService,
    private fb: FormBuilder,) { }

  ngOnInit(): void {   

    this.oprLogForm = this.fb.group({
      WorkOrderId: ['', Validators.required],
      OperationId: ['', Validators.required],
      OperationStatus: ['', [Validators.required]],      
      OpStartRunTime: [''],
      OpStartRunTime1: [''],   
      OpPauseRunTime: [''],
      OpPauseRunTime1: [''],
      OpQtyDone: ['', [Validators.pattern("^[0-9]*$")]],   
    });   
  
    this.operationStatusCollection = this.localDataService.getOperationStatusToDisplayForOperator();
    this.getWorkOrderList();

    this.oprLogForm.controls.OpPauseRunTime1.disable();
    this.oprLogForm.controls.OpStartRunTime1.disable();
  }

  
  getWorkOrderList() {
    this.dataService.getWorkOrderList()
      .subscribe(
        data => {
          this.workOrders = data;
        },
        error => {
          console.log(error);
          /*
          if (error.status === 401)            
            this.apiResponse = 'Un-Authorized !';
          else
            this.apiResponse = 'Error !';
          
          this.responseColor = 'red';
          this.workOrders = [];  
          */
        }
      );
  }
  
  getOperationList(e) {
    console.log(e.target.value);
    this.operations = [];
    this.oprLogForm.controls['OperationId'].setValue('');
    this.opQtyData = '';

    this.dataService.getOperationList(e.target.value)
      .subscribe(
        data => {     
          this.operations = data;
        },
        error => {
          console.log(error);
          /*
          if (error.status === 401)            
            this.apiResponse = 'Un-Authorized !';
          else
            this.apiResponse = 'Error !';
          
          this.responseColor = 'red';
          this.workOrders = [];     
          */
        });
  }
  getOpQtyData(e) {
    if (e.target.value !== '') {
      this.dataService.getOperationQtyData(e.target.value)
      .subscribe(
        data => {          
          if (data.statusCode !== -1)
            this.opQtyData = "[ Qty Done : " + data.qtyDone + ", Qty Req : " + data.qtyRequired + " ]";
          else
            this.opQtyData = data.message;
        },
        error => {
          console.log(error);
        });
    }
    else
      return; 
  }
  get oprLogFormControl() {
    return this.oprLogForm.controls;
  }

  resetOprLog() {    
    this.oprLogForm.reset();

    this.timeStartRunTime = { hour: 13, minute: 30 };
    this.timePauseRunTime = {hour: 13, minute: 30};
    this.meridian = true;       
    
    /*
    this.oprLogForm.controls['OperationId'].setValue('');
    this.oprLogForm.controls['WorkOrderId'].setValue('');
    this.oprLogForm.controls['OperationStatus'].setValue('');
    */
    this.opQtyData = '';
    this.submitted = false;

    this.modelErrors = [];
    this.apiResponse = '';

    this.oprLogForm.controls.OpPauseRunTime.disable();
    this.oprLogForm.controls.OpPauseRunTime1.disable();
    this.oprLogForm.controls.OpStartRunTime.disable();
    this.oprLogForm.controls.OpStartRunTime1.disable();
  } 

  goBack() {
    this.router.navigate(['/home']);
  }

  checkForNumbersOnly(newVal) {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal))
      // console.log('ok');
      return true;
    else
      // console.log('Only Numbers Allowed !!!');
      return false;
  }

  setVisibility(e) {
    console.log(e.target.value);
    this.oprLogForm.controls['OpQtyDone'].setValue('');
    if (e.target.value === "0") {     
      this.oprLogForm.controls.OpPauseRunTime.disable();
      this.oprLogForm.controls.OpPauseRunTime1.disable();

      this.oprLogForm.controls.OpStartRunTime.enable();
      this.oprLogForm.controls.OpStartRunTime1.enable();      
    }
    else {
      this.oprLogForm.controls.OpPauseRunTime.enable();
      this.oprLogForm.controls.OpPauseRunTime1.enable();

      this.oprLogForm.controls.OpStartRunTime.disable();
      this.oprLogForm.controls.OpStartRunTime1.disable();
    }
  }

  onSubmit(): void {

    this.submitted = true;
    
    if (this.oprLogForm.valid) {
      

      this.oprLogModel.opQtyDone = this.oprLogForm.value["OpQtyDone"];
      this.oprLogModel.workOrderId = this.oprLogForm.value["WorkOrderId"];
      this.oprLogModel.operationId = this.oprLogForm.value["OperationId"];
      this.oprLogModel.operationStatus = this.oprLogForm.value["OperationStatus"];
 
      // start_running
      if (this.oprLogForm.value["OperationStatus"] === "0") {
        
        this.oprLogModel.opQtyDone = 0;

        if (this.oprLogForm.value["OpStartRunTime"] !== "" && this.oprLogForm.value["OpStartRunTime"] !== undefined) {

          console.log('start run time date ,,,', this.oprLogForm.value["OpStartRunTime"]);

          var opStartRunTimeDateObj = this.oprLogForm.value["OpStartRunTime"];
                  
          var date = new Date(opStartRunTimeDateObj);
          date.setHours(this.timeStartRunTime.hour, this.timeStartRunTime.minute, 0);   // Set hours, minutes and seconds
          console.log(date.toString());

          this.oprLogModel.opStartRunTime = new Date(date).toISOString();
          this.oprLogModel.opPauseRunTime = null;
        }
        else {
          console.log('form-invalid,,, need start-run-time!!!');
          this.startRunTimeError = 'Need Start-Run-Time!';
          this.pauseRunTimeError = '';
          // return;
        }
      }
    
      // pause_running
      if (this.oprLogForm.value["OperationStatus"] === "1") {
        if (this.oprLogForm.value["OpPauseRunTime"] !== "" && this.oprLogForm.value["OpPauseRunTime"] !== undefined) {
          var opPauseRunTimeDateObj = this.oprLogForm.value["OpPauseRunTime"];
                 
          var date = new Date(opPauseRunTimeDateObj);
          date.setHours(this.timePauseRunTime.hour, this.timePauseRunTime.minute, 0);   // Set hours, minutes and seconds
          console.log(date.toString());

          this.oprLogModel.opPauseRunTime = new Date(date).toISOString();
          // this.oprLogModel.opPauseRunTime = date;
          this.oprLogModel.opStartRunTime = null;
          this.pauseRunTimeError = '';
        }
        else {
          console.log('form-invalid,,, need pause-run-time!!!');
          this.pauseRunTimeError = 'Need Pause-Run-Time!';
          this.startRunTimeError = '';
          // return;
        }

        if (this.oprLogForm.value["OpQtyDone"] !== "") {
          this.oprLogModel.opQtyDone = Number(this.oprLogForm.value["OpQtyDone"]);
          this.qtyDoneError = '';
        }
        else {
          console.log('form-invalid,,, need qty-done!!!');
          this.qtyDoneError = 'Need Qty-Done!';
          // return;
        }

        // comment below to check for server side model validation
        // if (this.pauseRunTimeError !== '' || this.qtyDoneError !== '')
          // return;
      }
     


     

      console.log('form valid!');
      this.pauseRunTimeError = '';
      this.startRunTimeError = '';

      this.oprLogModel.userId = this.localDataService.getMyUserId();

      console.log(this.oprLogModel);

      this.dataService.createOperatorLog(this.oprLogModel)
        .subscribe(
          response => {
            this.modelErrors = [];
            this.apiResponse = '';

            console.log(response);

            if(response.responseCode===0){
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              
              setTimeout(() => {              
                this.resetOprLog();    
              }, 2000);  
            }
            else{
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            // console.log(error);
            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Operator-Log-Create');
            }
            else
              this.apiResponse = 'Error !';            
          }
        );

    }
    else {
      console.log('form in-valid!');
    }
    
  } 
}

<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header componentHeader">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>
                                <div>
                                    Create Operator - Log
                                </div>
                            </h4>                          
                            <h5 *ngIf="apiResponse">
                                <p></p>
                                <span [style.color]="responseColor">
                                    {{apiResponse}}
                                </span>
                            </h5>
                            <h5 *ngIf="modelErrors.length > 0">
                                <ul [style.color]="responseColor">
                                    <li *ngFor="let error of modelErrors">
                                        {{ error }}
                                    </li>
                                </ul>
                            </h5>
                        </div>
                        <div class="col-md-2 ">
                            <button type="button" 
                                (click)="goBack()" 
                                class="btn btn-primary cancelBtn">
                                <i class="bi bi-arrow-return-left"></i> 
                                Back
                            </button>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form class="form-oprLog" 
                        [formGroup]="oprLogForm" 
                        (ngSubmit)="onSubmit()">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>Work-Order</label>
                                    <select 
                                        class="form-control" 
                                        (change)="getOperationList($event)"
                                        formControlName="WorkOrderId">
                                        <option value="">Choose Work-Order</option>
                                        <option value={{wo.value}} *ngFor="let wo of workOrders">
                                            {{wo.text}}
                                        </option>
                                    </select>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(oprLogFormControl.WorkOrderId.touched || submitted) && oprLogFormControl.WorkOrderId.errors?.required">
                                        Work-Order is required
                                    </div>
                                </div>   
                                <p></p>                    
                                <div class="form-group">
                                    <label>Operation</label>
                                    <br />
                                    <span class="opQtyData" *ngIf="opQtyData">{{opQtyData}}</span>                                    
                                    <select class="form-control" 
                                        (change)="getOpQtyData($event)"
                                        formControlName="OperationId">
                                        <option value="">Choose Operation</option>
                                        <option value={{op.value}} *ngFor="let op of operations">
                                            {{op.text}}
                                        </option>
                                    </select>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(oprLogFormControl.OperationId.touched || submitted) && oprLogFormControl.OperationId.errors?.required">
                                        Operation is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Operation-Status</label>
                                    <select 
                                        (change)="setVisibility($event)"
                                        class="form-control" 
                                        formControlName="OperationStatus">
                                        <option value="">Choose Operation-Status</option>
                                        <option value={{op.value}} *ngFor="let op of operationStatusCollection">
                                            {{op.opStatus}}
                                        </option>
                                    </select>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(oprLogFormControl.OperationStatus.touched || submitted) && oprLogFormControl.OperationStatus.errors?.required">
                                        Operation-Status is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Qty-Done</label>
                                    <br />
                                    <span class="runTimeCheckError">{{qtyDoneError}}</span>
                                    <input type="text" 
                                        class="form-control qtyField" 
                                        formControlName="OpQtyDone" />
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(oprLogFormControl.OpQtyDone.touched || submitted) && oprLogFormControl.OpQtyDone.errors?.pattern">
                                        Only Numbers are allowed
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-1 "></div>
                            <div class="col-md-5 ">  
                                <div class="form-group">
                                    <label>[Start] Run Time</label>
                                    <br />
                                    <span class="runTimeCheckError">{{startRunTimeError}}</span>
                                    <div class="input-group">
                                        <input 
                                            [attr.disabled]="true"
                                            [bsConfig]="{ isAnimated: true, dateInputFormat: 'YYYY-MM-DD' }" 
                                            formControlName="OpStartRunTime" 
                                            type="text"
                                            placeholder="Start Run Time" 
                                            class="form-control" 
                                            bsDatepicker>    
                                        <!-- 
                                        <select class="form-control" formControlName="StartRunTimeHr">
                                            <option value="">Hr</option>
                                            <option value={{h.value}} *ngFor="let h of hours">
                                                {{h.value}}
                                            </option>
                                        </select>
                                        &nbsp;
                                        <select class="form-control" formControlName="StartRunTimeMin">
                                            <option value="">Min</option>
                                            <option value={{m.value}} *ngFor="let m of minutes">
                                                {{m.value}}
                                            </option>
                                        </select>  
                                        -->
                                    </div> 
                                    <div class="input-group">
                                        <ngb-timepicker 
                                            formControlName="OpStartRunTime1" 
                                            [(ngModel)]="timeStartRunTime" 
                                            [meridian]="meridian">
                                        </ngb-timepicker>
                                        <!-- 
                                        <hr>
                                        <pre>Selected time: {{timeStartRunTime | json}}</pre>
                                        -->
                                    </div>
                                </div>
                                <p></p>
                                <div                                 
                                    class="form-group">
                                    <label>[Pause] Run Time</label>
                                    <br />
                                    <span class="runTimeCheckError">{{pauseRunTimeError}}</span>
                                    <div class="input-group">
                                        <input 
                                            [attr.disabled]="true"
                                            [bsConfig]="{ isAnimated: true, dateInputFormat: 'YYYY-MM-DD' }" 
                                            formControlName="OpPauseRunTime"
                                            type="text" 
                                            placeholder="Pause Run Time" 
                                            class="form-control" 
                                            bsDatepicker>                                    
                                    </div>
                                    <div class="input-group">
                                        <ngb-timepicker    
                                            class="form-control"                                  
                                            formControlName="OpPauseRunTime1" 
                                            [(ngModel)]="timePauseRunTime" 
                                            [meridian]="meridian">
                                        </ngb-timepicker>                                       
                                    </div>
                                </div>
                            </div>
                        </div>

                        <hr />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-5">
                                    <button type="submit" 
                                        class="btn btn-success">
                                        Create New Operator Log
                                    </button>
                                </div>
                                <div class="col-sm-3"></div>
                                <div class="col-sm-4 ">
                                    <button type="button" 
                                        (click)="resetOprLog()" 
                                        class="btn btn-primary cancelBtn">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Create_Operator_Log/Create_Operator_Log.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import OperatorLogService from "../../services/operatorLog.service";
import { getOperationStatusForOperatorToDisplay } from "../../services/local.service";

import { useNavigate } from "react-router";
import { useLocation } from "react-router-dom";

import Moment from "moment";

import DateTimePicker from "react-datetime-picker";

const Create_Operator_Log = () => {
  let navigate = useNavigate();
  let location = useLocation();

  // reset form
  // form reference
  const formRef = useRef(null);

  const [operationStatusCollection, setOperationStatusCollection] = useState(
    []
  );
  const [workOrders, setWorkOrders] = useState([]);
  const [operations, setOperations] = useState([]);
  const [opQtyData, setOpQtyData] = useState("");

  const [modelErrors, setModelErrors] = useState([]);
  const [opCreateResponse, setOpCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  const [startControl, setStartControl] = useState(false);
  const [pauseControl, setPauseControl] = useState(false);

  // startRunTimeValue, pauseRunTimeValue are NOT part of the form-control
  // so validation is separate @ submit
  // const [startRunTimeValue, onStartTimeChange] = useState(new Date());
  const [startRunTimeValue, onStartTimeChange] = useState(null);
  const [pauseRunTimeValue, onPauseTimeChange] = useState(null);

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Operator"))
      navigate("/un-auth");
    else {
      setOperationStatusCollection(getOperationStatusForOperatorToDisplay());
      getWorkOrderList();
    }
  }, []);

  const setField = (field, value) => {
    // workorderid
    if (field === "workOrderId") {
      setOperations([]);
      setOpQtyData("");
      if (value !== "") {
        console.log("getting operations for wo#", value);
        getOperationList(value);
      }
    }

    // operationid
    if (field === "operationId") {
      setOpQtyData("");
      if (value !== "") {
        console.log("getting operation qty data for op#", value);
        getOpQtyData(value);
      }
    }

    // operationstatus
    if (field === "operationStatus") {
      // Start_Running
      if (value === "0") {
        // enable start_run_time
        setStartControl(true);
        // disable pause_run_time && qty-done
        setPauseControl(false);
      }
      // Pause_Running
      else if (value === "1") {
        // disable start_run_time
        setStartControl(false);
        // enable pause_run_time && qty-done
        setPauseControl(true);
      } else {
        setStartControl(false);
        setPauseControl(false);
      }
    }

    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const getWorkOrderList = () => {
    OperatorLogService.getWorkOrderList()
      .then((response) => {
        console.log(response.data);
        setWorkOrders(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const getOperationList = (selectedWoId) => {
    OperatorLogService.getOperationList(selectedWoId)
      .then((response) => {
        console.log(response.data);
        setOperations(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const getOpQtyData = (selectedOpId) => {
    OperatorLogService.getOperationQtyData(selectedOpId)
      .then((response) => {
        if (response.data.statusCode !== -1) {
          setOpQtyData(
            "[ Qty Done : " +
              response.data.qtyDone +
              ", Qty Req : " +
              response.data.qtyRequired +
              " ]"
          );
        } else {
          setOpQtyData(response.data.message);
        }
      })
      .catch((e) => {
        console.log(e);
      });
  };

  const goBack = (e) => {
    navigate("/home");
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setOpCreateResponse({});
    setModelErrors([]);
  };

  const findFormErrors = () => {
    setModelErrors([]);
    setOpCreateResponse({});

    const { operationId, workOrderId, operationStatus, opQtyDone } = form;
    const newErrors = {};

    if (!operationId || operationId === "")
      newErrors.operationId = "Operation is Required!";
    if (!workOrderId || workOrderId === "")
      newErrors.workOrderId = "Work-Order is Required!";
    if (!operationStatus || operationStatus === "")
      newErrors.operationStatus = "Operation-Status is Required!";

    if (!(!opQtyDone || opQtyDone === "")) {
      if (!checkForNumbersOnly(opQtyDone))
        newErrors.opQtyDone = "Only Numbers are Allowed!";
    }

    if (pauseControl && (opQtyDone === "" || opQtyDone === undefined)) {
      newErrors.opQtyDone = "Qty-Done is Required!";
    }

    return newErrors;
  };
  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    // startRunTimeValue, pauseRunTimeValue are NOT part of the form-control
    // so validation is separate @ submit
    if (startControl && startRunTimeValue === null) {
      newErrors.startRunTimeValue = "Start Run Time is Required!";
      newErrors.pauseRunTimeValue = "";
    }
    if (pauseControl && pauseRunTimeValue === null) {
      newErrors.pauseRunTimeValue = "Pause Run Time is Required!";
      newErrors.startRunTimeValue = "";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      console.log("form is valid!");

      var oprLogModel = {
        operationId: form.operationId,
        workOrderId: form.workOrderId,
        operationStatus: form.operationStatus,
        opQtyDone: form.opQtyDone,
        opStartRunTime: startRunTimeValue,
        opPauseRunTime: pauseRunTimeValue,
        userId: "2bf8c0ce-2733-4d08-bcaa-2783ed06cb45",
        operatorId: 0,
      };

      if (startControl) {
        oprLogModel.opQtyDone = 0;
        oprLogModel.opPauseRunTime = null;
        oprLogModel.opStartRunTime = startRunTimeValue;
      }
      if (pauseControl) {
        oprLogModel.opQtyDone = Number(form.opQtyDone);
        oprLogModel.opStartRunTime = null;
        oprLogModel.opStartRunTime = pauseRunTimeValue;
      }

      console.log(oprLogModel);

      // api call
      OperatorLogService.createOperatorLog(oprLogModel)
        .then((response) => {
          setModelErrors([]);
          setOpCreateResponse({});
          console.log(response.data);
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setOpCreateResponse({});
        });
    }
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const renderOptionsForWorkOrders = () => {
    return workOrders.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.text}>
          {dt.text}
        </option>
      );
    });
  };
  const renderOptionsForOperations = () => {
    return operations.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.text}>
          {dt.text}
        </option>
      );
    });
  };
  const renderOptionsForOperationStatus = () => {
    return operationStatusCollection.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.opStatus}>
          {dt.opStatus}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-10 mx-auto">
            <div className="card">
              <div className="card-header">
                <div className="row">
                  <div className="col-md-10 mx-auto">
                    <h3>Create Operator - Log</h3>
                    <p></p>
                  </div>
                  <div className="col-md-2 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="workOrderId">
                        <Form.Label>Work-Order</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.workOrderId}
                          onChange={(e) => {
                            setField("workOrderId", e.target.value);
                          }}
                        >
                          <option value="">Select Work-Order</option>
                          {renderOptionsForWorkOrders()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.workOrderId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="operationId">
                        <Form.Label>Operation</Form.Label>

                        <br />
                        {opQtyData && (
                          <span className="opQtyData">{opQtyData}</span>
                        )}

                        <Form.Control
                          as="select"
                          isInvalid={!!errors.operationId}
                          onChange={(e) => {
                            setField("operationId", e.target.value);
                          }}
                        >
                          <option value="">Select Operation</option>
                          {renderOptionsForOperations()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.operationId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="operationStatus">
                        <Form.Label>Operation Status</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.operationStatus}
                          onChange={(e) => {
                            setField("operationStatus", e.target.value);
                          }}
                        >
                          <option value="">Select Operation Status</option>
                          {renderOptionsForOperationStatus()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.operationStatus}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="opQtyDone">
                        <Form.Label>Qty-Done</Form.Label>
                        <Form.Control
                          disabled={!pauseControl}
                          className="qtyField"
                          type="text"
                          isInvalid={!!errors.opQtyDone}
                          onChange={(e) =>
                            setField("opQtyDone", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.opQtyDone}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Label>Start Run Time</Form.Label>
                      <br />
                      {console.log(startRunTimeValue)}
                      <DateTimePicker
                        disabled={!startControl}
                        controlId="startRunTimeValue"
                        onChange={onStartTimeChange}
                        value={startRunTimeValue}
                      />
                      {errors.startRunTimeValue !== "" && (
                        <div className="timeError">
                          {errors.startRunTimeValue}
                        </div>
                      )}
                      <p></p>
                      <Form.Label>Pause Run Time</Form.Label>
                      <br />
                      <DateTimePicker
                        disabled={!pauseControl}
                        controlId="pauseRunTimeValue"
                        onChange={onPauseTimeChange}
                        value={pauseRunTimeValue}
                      />
                      {errors.pauseRunTimeValue && (
                        <div className="timeError">
                          {errors.pauseRunTimeValue}
                        </div>
                      )}
                    </div>
                  </div>
                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Create New Operator Log
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Cancel
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Create_Operator_Log;
