// NgApp-WOT/src/app/work-order-remove/work-order-remove.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-work-order-remove',
  templateUrl: './work-order-remove.component.html',
  styleUrls: ['./work-order-remove.component.css']
})
export class WorkOrderRemoveComponent implements OnInit {

  woId: string;
  wo: any;
  
  apiResponse = '';
  responseColor = '';

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {   
    
    this.woId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.woId)) {
      console.log('Not a Number!');
      this.router.navigate(['/work-order']);
    }
    else {
      this.dataService.getWorkOrder(Number(this.woId))
        .subscribe(
          data => {
            if(data===null){
              console.log('work-order not found!');
           
              this.apiResponse = 'Work-Order Not Found!';
              this.responseColor = 'red';
            }
            else {
              console.log(data);
              this.apiResponse = '';
              this.responseColor = 'green';   
                         
              this.wo = data;              
            }
          },
          error => {
            console.log(error);
            
            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          });
    }
  }

  removeWo(wo) {
    this.dataService.removeWorkOrder(wo)
        .subscribe(
          response => {

            if (response.responseCode === 0) {
              
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';           
              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/work-order']);
              }, 2000);  
            }
            else {
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
  }

  cancelRemoveWo() {
     this.router.navigate(['/work-order']);
  }


}

<div class="container">
    <div class="col-md-10 mx-auto">
        <div class="card">
            <div class="card-header componentHeader">
                <h4>
                    <div>
                        #&nbsp;{{woId}}) Work-Order - Remove
                    </div>
                </h4>
                <h5 *ngIf="wo">
                    <span class="labelColor">
                        Are you sure wants to remove work-order?
                    </span>
                </h5>
                <p></p>
                <h5 *ngIf="apiResponse">
                    <span [style.color]="responseColor">
                        {{apiResponse}}
                    </span>
                </h5>
            </div>

            <!-- *ngIf="!apiResponse" -->
            <div *ngIf="wo" class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-10">
                            <span class="labelColor">Customer Name :</span> [# {{wo.customerOrderId}}]&nbsp;{{wo.customerOrder.customerName}}
                            <p></p>
                            <span class="labelColor">Work-Order Start Date #</span> {{wo.workOrderStartDate | date: "dd-MMM,yyyy"}}
                            <p></p>
                            <span class="labelColor">Work-Order Status #</span> {{localDataService.getWorkOrderStatus(wo.workOrderStatus)}}
                            <p></p>
                            <span class="labelColor">Status Note</span> <br />
                            {{wo.statusNote}}
                            <p></p>
                        </div>
                    </div>

                    <p></p>
                    <hr />
                    <div class="row">
                        <div class="col-sm-6">
                            <button type="button" 
                                (click)="removeWo(wo)" class="btn btn-danger">
                                Remove Work-Order
                            </button>
                        </div>
                        <div class="col-sm-6">
                            <button type="button" 
                                (click)="cancelRemoveWo()" 
                                class="btn btn-primary cancelBtn">
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/WorkOrder_Remove/WorkOrder_Remove.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import WorkOrderService from "../../services/workOrder.service";

import { useNavigate } from "react-router";

import Moment from "moment";

import {
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../services/local.service";

const WorkOrder_Remove = () => {
  let navigate = useNavigate();

  let { id } = useParams();
  const [wo, setWo] = useState({});
  const [woRemoveResponse, setWoRemoveResponse] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getWorkOrder(id);
  }, []);

  const getWorkOrder = (id) => {
    console.log("Removing Work-Order : ", id);
    if (checkForNumbersOnly(id)) {
      WorkOrderService.getWorkOrder(id)
        .then((response) => {
          if (response.data !== "") {
            console.log(response.data);
            setWo(response.data);
          } else {
            setWo({ workOrderId: 0 });
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/work-order");
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // api call
    WorkOrderService.removeWorkOrder(wo)
      .then((response) => {
        console.log(response.data);
        setWoRemoveResponse({});
        var woRemoveResponse = {
          responseCode: response.data.responseCode,
          responseMessage: response.data.responseMessage,
        };

        setWoRemoveResponse(woRemoveResponse);
        if (response.data.responseCode === 0) {
          setTimeout(() => {
            navigate("/work-order");
          }, 3000);
        }
      })
      .catch((error) => {
        setWoRemoveResponse({});
      });
  };

  const goBack = (e) => {
    navigate("/work-order");
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-10 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Remove Work-Order</h3>
                <h5>
                  <span className="headerText">
                    Are you sure wants to remove work-order?
                  </span>
                </h5>
                <p></p>{" "}
                {woRemoveResponse && woRemoveResponse.responseCode === -1 ? (
                  <span className="woRemoveError">
                    {woRemoveResponse.responseMessage}
                  </span>
                ) : (
                  <span className="woRemoveSuccess">
                    {woRemoveResponse.responseMessage}
                  </span>
                )}
              </div>
              <div className="card-body">
                <div className="container">
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <span className="headerText">Work-Order </span>
                      {id ? (
                        <span>&nbsp;# {id}</span>
                      ) : (
                        <span>&nbsp; # N/A</span>
                      )}
                      <p></p>

                      <span className="headerText">Customer Name</span>
                      {wo.customerOrderId ? (
                        <span>
                          &nbsp;&nbsp;[# {wo.customerOrderId}]{" "}
                          {wo.customerOrder.customerName}
                        </span>
                      ) : (
                        <span>&nbsp; # N/A</span>
                      )}
                      <p></p>
                      <span className="headerText">Work-Order Start Date</span>
                      {wo.workOrderStartDate ? (
                        <span>
                          {" "}
                          #{" "}
                          {Moment(wo.workOrderStartDate).format("DD-MMM-YYYY")}
                        </span>
                      ) : (
                        <span>&nbsp; # N/A</span>
                      )}
                      <p></p>
                      <span className="headerText">Work-Order Status</span>
                      {wo.workOrderStatus || wo.workOrderStatus === 0 ? (
                        <span> # {getWorkOrderStatus(wo.workOrderStatus)}</span>
                      ) : (
                        <span>&nbsp; # N/A</span>
                      )}
                      <p></p>
                      <span className="headerText">Note</span>
                      {wo.statusNote ? (
                        <span>
                          <br />
                          {wo.statusNote}
                        </span>
                      ) : (
                        <span>&nbsp; # N/A</span>
                      )}
                    </div>
                  </div>
                </div>

                <p></p>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Button
                    className="btn btn-success"
                    type="button"
                    onClick={(e) => handleSubmit(e)}
                  >
                    Remove Work-Order
                  </Button>
                  <Button
                    className="btn btn-primary"
                    type="button"
                    onClick={(e) => goBack(e)}
                  >
                    <i className="bi bi-arrow-return-left"></i> Back
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WorkOrder_Remove;
