// NgApp-WOT/src/app/work-order-edit/work-order-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-work-order-edit',
  templateUrl: './work-order-edit.component.html',
  styleUrls: ['./work-order-edit.component.css']
})
export class WorkOrderEditComponent implements OnInit {

  workOrderStatusCollection: Array<any>;
  
  woId: string;
  coId: string;

  woForm: FormGroup;
  submitted = false;
  woModel = {
    workOrderId: 0,
    customerOrderId: 0,
    workOrderStartDate: new Date(),
    workOrderStatus: 0,
    statusNote: '',
  };

  apiResponse = '';
  responseColor = '';
  modelErrors = [];
  
  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {
     this.woForm = this.fb.group({
        WorkOrderStartDate: [''],
        WorkOrderStatus: ['', [Validators.required]],      
        StatusNote: [''],
     });
    
    this.workOrderStatusCollection = this.localDataService.getWorkOrderStatusToDisplay();

    this.woId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.woId)) {
      console.log('Not a Number!');
      this.router.navigate(['/work-order']);
    }
    else {
      this.dataService.getWorkOrder(Number(this.woId))
        .subscribe(
          data => {
            if(data===null){
              console.log('work-order not found!');
           
              this.apiResponse = 'Work-Order Not Found!';
              this.responseColor = 'red';
            }
            else{
              this.apiResponse = '';
              this.responseColor = 'green';       

              if (data.workOrderStartDate === null) {
                 this.woForm.setValue({                
                  WorkOrderStatus: data.workOrderStatus,
                  StatusNote: data.statusNote,           
                  WorkOrderStartDate: new Date(),
                });
              }
              else {
                  this.woForm.setValue({                
                  WorkOrderStatus: data.workOrderStatus,
                  StatusNote: data.statusNote,           
                  WorkOrderStartDate: new Date(Date.parse(data.workOrderStartDate)),
                });
              }


           
              this.coId = data.customerOrderId;
              console.log(data);
            }
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          });
    }
  }

  get woFormControl() {
    return this.woForm.controls;
  }

  onSubmit(): void {
    this.submitted = true;
    if (this.woForm.valid) {
      console.log('form valid!');     
    
      this.woModel.statusNote = this.woForm.value["StatusNote"];   
      this.woModel.workOrderStatus = this.woForm.value["WorkOrderStatus"];   
      this.woModel.workOrderStartDate = this.woForm.value["WorkOrderStartDate"];
      this.woModel.workOrderId = Number(this.woId);
      this.woModel.customerOrderId = Number(this.coId);
      console.log(this.woModel);  

      this.dataService.editWorkOrder(this.woModel)
        .subscribe(
          response => {
            console.log(response);
            this.modelErrors = [];
            this.apiResponse = '';

            if (response.responseCode === 0) {              
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetWo();
              this.submitted = false;
              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/work-order']);
              }, 2000);  
            }
            else {
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Customer-Order-Create');
            }
            else
              this.apiResponse = 'Error !';            
          }
        );
    }
    else {
      console.log('form in-valid!');
    }
  }
  
  resetWo(){
    this.woForm.reset();
    this.submitted = false;
  }

}

<div class="container">
    <div class="col-md-7 mx-auto">
        <div class="card">
            <div class="card-header componentHeader">
                <h4>
                    <div>
                        #{{woId}}) Work-Order - Edit
                    </div>
                </h4>
                <h5 *ngIf="apiResponse">
                    <span [style.color]="responseColor">
                        {{apiResponse}}
                    </span>
                </h5>
                <h5 *ngIf="modelErrors.length > 0">
                    <ul [style.color]="responseColor">
                        <li *ngFor="let error of modelErrors">
                            {{ error }}
                        </li>
                    </ul>
                </h5>
            </div>
            <div class="card-body">
                <form class="form-wo" [formGroup]="woForm" (ngSubmit)="onSubmit()">

                    <div class="row">
                        <div class="col-md-1 mx-auto"></div>
                        <div class="col-md-10 mx-auto">
                            <div class="form-group">
                                <label>Work-Order Status</label>
                                <select class="form-control" formControlName="WorkOrderStatus">
                                    <option value="">Choose Work-Order Status</option>
                                    <option value={{wo.value}} *ngFor="let wo of workOrderStatusCollection">
                                        {{wo.woStatus}}
                                    </option>
                                </select>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(woFormControl.WorkOrderStatus.touched || submitted) && woFormControl.WorkOrderStatus.errors?.required">
                                    Work-Order Status is required
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Work-Order Start Date</label>
                                <div class="input-group dateField">
                                    <input 
                                        [bsConfig]="{ isAnimated: true, dateInputFormat: 'YYYY-MM-DD' }" 
                                        formControlName="WorkOrderStartDate"
                                        type="text" 
                                        placeholder="Work-Order Start Date" 
                                        class="form-control" 
                                        bsDatepicker>
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Status Note</label>
                                <textarea type="text" class="form-control" formControlName="StatusNote">
                                </textarea>
                            </div>
                        </div>
                        <div class="col-md-1 mx-auto"></div>
                    </div>


                    <hr />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" class="btn btn-success">
                                    Edit Work-Order
                                </button>
                            </div>
                            <div class="col-sm-6">
                                <button type="button" (click)="resetWo()" class="btn btn-primary cancelBtn">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/WorkOrder_Edit/WorkOrder_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import WorkOrderService from "../../services/workOrder.service";

import { useNavigate } from "react-router";

import Moment from "moment";

import { getWorkOrderStatusToDisplay } from "../../services/local.service";

const WorkOrder_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [workOrderStatusCollection, setWorkOrderStatusCollection] = useState(
    []
  );
  const [wo, setWo] = useState({});

  const [modelErrors, setModelErrors] = useState([]);

  const [woEditResponse, setWoEditResponse] = useState({});

  // form
  const [workOrderStatus, setWorkOrderStatus] = useState("");
  const [workOrderStartDate, setWorkOrderStartDate] = useState("");
  const [statusNote, setStatusNote] = useState("");
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      setWorkOrderStatusCollection(getWorkOrderStatusToDisplay());
      getWorkOrder(id);
    }
  }, []);

  const getWorkOrder = (id) => {
    console.log("Editing Work-Order : ", id);
    WorkOrderService.getWorkOrder(id)
      .then((response) => {
        if (response.data === "") {
          // data not found on server!

          setWo({});
          var woEditResponse = {
            responseCode: -1,
            responseMessage: "Work-Order Not Found!",
          };

          setWoEditResponse(woEditResponse);
        } else {
          console.log(response.data);

          setWo(response.data);

          setWorkOrderStatus(response.data.workOrderStatus);

          if (response.data.statusNote === null) {
            setStatusNote("");
          } else {
            setStatusNote(response.data.statusNote);
          }

          if (response.data.workOrderStartDate === null) {
            setWorkOrderStartDate("");
          } else {
            // convert c# date into react-bootstrap-date picker date format
            setWorkOrderStartDate(
              new Date(response.data.workOrderStartDate)
                .toISOString()
                .slice(0, 10)
            );
          }
        }
      })
      .catch((e) => {
        console.log(e);
      });
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleWorkOrderStartDate = (event) => {
    setWorkOrderStartDate(event.target.value);
    if (!errors[workOrderStartDate])
      setErrors({
        ...errors,
        workOrderStartDate: "",
      });
  };
  const handleWorkOrderStatus = (event) => {
    setWorkOrderStatus(event.target.value);
    if (!errors[workOrderStatus])
      setErrors({
        ...errors,
        workOrderStatus: "",
      });
  };
  const handleStatusNote = (event) => {
    setStatusNote(event.target.value);
    if (!errors[statusNote])
      setErrors({
        ...errors,
        statusNote: "",
      });
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!workOrderStatus || workOrderStatus === "")
      newErrors.workOrderStatus = "Work-Order Status is Required!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      // for (let prop in error.response.data.errors) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var oDate = Moment(workOrderStartDate);
      var oCheck = oDate.isValid();
      if (!oCheck) setWorkOrderStartDate("");

      var woModel = {
        customerOrderId: wo.customerOrderId,
        workOrderId: wo.workOrderId,
        workOrderStartDate: workOrderStartDate,
        workOrderStatus: workOrderStatus,
        statusNote: statusNote,
      };
      console.log(woModel);
      // api call
      WorkOrderService.editWorkOrder(woModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setWoEditResponse({});
          var woEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          if (response.data.responseCode === 0) resetForm();

          setWoEditResponse(woEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              navigate("/work-order");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setWoEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setWorkOrderStartDate("");
    setWorkOrderStatus("");
    setStatusNote("");
    setWoEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);
  const renderOptionsForWorkOrderStatus = () => {
    return workOrderStatusCollection.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.woStatus}>
          {dt.woStatus}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-10 mx-auto">
            <div className="card">
              <div className="card-header header">
                <h3>Edit Work-Order # {id}</h3>
                <p></p>
                <h4>Customer Order # {wo.customerOrderId}</h4>
                <p></p>
                {woEditResponse && woEditResponse.responseCode === -1 ? (
                  <span className="woEditError">
                    {woEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="woEditSuccess">
                    {woEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="workOrderStartDate">
                        <Form.Label>Work-Order Start Date</Form.Label>
                        <Form.Control
                          type="date"
                          value={workOrderStartDate}
                          name="workOrderStartDate"
                          placeholder="Work-Order Start Date"
                          isInvalid={!!errors.workOrderStartDate}
                          onChange={(e) => handleWorkOrderStartDate(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.workOrderStartDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="workOrderStatus">
                        <Form.Label>Work-Order Status</Form.Label>
                        <Form.Control
                          as="select"
                          value={workOrderStatus}
                          isInvalid={!!errors.workOrderStatus}
                          onChange={(e) => handleWorkOrderStatus(e)}
                        >
                          <option value="">Select Work-Order Status</option>
                          {renderOptionsForWorkOrderStatus()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.workOrderStatus}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="statusNote">
                        <Form.Label>Note</Form.Label>
                        <Form.Control
                          as="textarea"
                          value={statusNote}
                          rows="3"
                          isInvalid={!!errors.statusNote}
                          onChange={(e) => handleStatusNote(e)}
                        />
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Work-Order
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default WorkOrder_Edit;
