// reactapp-wot/src/components/CustomerOrder_Edit/CustomerOrder_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import CustomerOrderService from "../../services/customerOrder.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const CustomerOrder_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [modelErrors, setModelErrors] = useState([]);

  const [coEditResponse, setCoEditResponse] = useState({});

  // form
  const [customerName, setCustomerName] = useState("");
  const [productName, setProductName] = useState("");
  const [productDesc, setProductDesc] = useState("");
  const [orderQty, setOrderQty] = useState(0);
  const [orderDate, setOrderDate] = useState("");
  const [orderDueDate, setOrderDueDate] = useState("");
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getCustomerOrder(id);
  }, []);

  const getCustomerOrder = (id) => {
    console.log("Editing Customer-Order : ", id);
    if (checkForNumbersOnly(id)) {
      CustomerOrderService.getCustomerOrder(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var coEditResponse = {
              responseCode: -1,
              responseMessage: "Customer-Order Not Found!",
            };

            setCoEditResponse(coEditResponse);
          } else {
            console.log(response.data);

            setCustomerName(response.data.customerName);
            setProductName(response.data.productName);
            setProductDesc(response.data.productDesc);
            setOrderQty(response.data.orderQuantity);
            setOrderDate(response.data.orderDate);
            setOrderDueDate(response.data.orderDueDate);
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/customer-order");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleCustomerName = (event) => {
    setCustomerName(event.target.value);
    if (!errors[customerName])
      setErrors({
        ...errors,
        customerName: "",
      });
  };
  const handleProductName = (event) => {
    setProductName(event.target.value);
    if (!errors[productName])
      setErrors({
        ...errors,
        productName: "",
      });
  };
  const handleProductDesc = (event) => {
    setProductDesc(event.target.value);
    if (!errors[productDesc])
      setErrors({
        ...errors,
        productDesc: "",
      });
  };
  const handleOrderQty = (event) => {
    setOrderQty(event.target.value);
    if (!errors[orderQty])
      setErrors({
        ...errors,
        orderQty: "",
      });
  };
  const handleOrderDate = (event) => {
    setOrderDate(event.target.value);
    if (!errors[orderDate])
      setErrors({
        ...errors,
        orderDate: "",
      });
  };
  const handleOrderDueDate = (event) => {
    setOrderDueDate(event.target.value);
    if (!errors[orderDueDate])
      setErrors({
        ...errors,
        orderDueDate: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!customerName || customerName === "")
      newErrors.customerName = "Customer Name is Required!";

    if (!productName || productName === "")
      newErrors.productName = "Product Name is Required!";

    if (!productDesc || productDesc === "")
      newErrors.productDesc = "Product Desc is Required!";

    if (!orderQty || orderQty === "")
      newErrors.orderQty = "Order Qty is Required!";
    else {
      if (!checkForNumbersOnly(orderQty))
        newErrors.orderQty = "Only Numbers are Allowed!";
    }

    if (!orderDate || orderDate === "")
      newErrors.orderDate = "Order Date is Required!";

    if (!orderDueDate || orderDueDate === "")
      newErrors.orderDueDate = "Order Due Date is Required!";

    if (orderDate > orderDueDate)
      newErrors.orderDate = "Order-Date Must be < Order-Due-Date!";

    if (orderDueDate < orderDate)
      newErrors.orderDueDate = "Order-Due-Date Must be >= Order-Date!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      // for (let prop in error.response.data.errors) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var oDate = Moment(orderDate);
      var oCheck = oDate.isValid();
      var odDate = Moment(orderDueDate);
      var odCheck = odDate.isValid();
      if (oCheck && odCheck) {
        var coModel = {
          customerName: customerName,
          productName: productName,
          productDesc: productDesc,
          orderQuantity: parseInt(orderQty),
          orderDate: orderDate,
          orderDueDate: orderDueDate,
          customerOrderId: parseInt(id),
        };

        console.log(coModel);
      } else {
        console.log("Invalid Date(s) !");
        var coEditResponse = {
          responseCode: -1,
          responseMessage: "Invalid Date(s) !",
        };
        setCoEditResponse(coEditResponse);
        setModelErrors([]);
      }
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setCustomerName("");
    setProductName("");
    setProductDesc("");
    setOrderQty(0);
    setOrderDate(undefined);
    setOrderDueDate(undefined);
    setCoEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-10 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Edit Part</h3>
                <p></p>{" "}
                {coEditResponse && coEditResponse.responseCode === -1 ? (
                  <span className="coEditError">
                    {coEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="coEditSuccess">
                    {coEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="customerName">
                        <Form.Label>Customer Name</Form.Label>
                        <Form.Control
                          value={customerName}
                          type="text"
                          isInvalid={!!errors.customerName}
                          onChange={(e) => handleCustomerName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.customerName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="productName">
                        <Form.Label>Product Name</Form.Label>
                        <Form.Control
                          value={productName}
                          type="text"
                          isInvalid={!!errors.productName}
                          onChange={(e) => handleProductName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.productName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="productDesc">
                        <Form.Label>Product Desc</Form.Label>
                        <Form.Control
                          value={productDesc}
                          as="textarea"
                          rows="3"
                          isInvalid={!!errors.productDesc}
                          onChange={(e) => handleProductDesc(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.productDesc}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-1 mx-auto"></div>
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="orderQty">
                        <Form.Label>Order Qty</Form.Label>
                        <Form.Control
                          value={orderQty}
                          className="qtyDisplay"
                          type="text"
                          isInvalid={!!errors.orderQty}
                          onChange={(e) => handleOrderQty(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderQty}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="orderDate">
                        <Form.Label>Order Date</Form.Label>
                        <Form.Control
                          type="date"
                          name="orderDate"
                          value={orderDate}
                          isInvalid={!!errors.orderDate}
                          onChange={(e) => handleOrderDate(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="orderDueDate">
                        <Form.Label>Order Due Date</Form.Label>
                        <Form.Control
                          type="date"
                          name="orderDueDate"
                          value={orderDueDate}
                          isInvalid={!!errors.orderDueDate}
                          onChange={(e) => handleOrderDueDate(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderDueDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Customer-Order
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default CustomerOrder_Edit;

// NgApp-WOT/src/app/customer-order-edit/customer-order-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-customer-order-edit',
  templateUrl: './customer-order-edit.component.html',
  styleUrls: ['./customer-order-edit.component.css']
})
export class CustomerOrderEditComponent implements OnInit {

  coId: string;

  coForm: FormGroup;
  submitted = false;
  coModel = { 
    customerOrderId: 0,
    customerName: '',
    productName: '',
    productDesc: '',
    orderQuantity: 0,
    orderDate: new Date(),
    orderDueDate: new Date(),
  };

  apiResponse = '';
  responseColor = '';
  modelErrors = [];
  
  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {
     this.coForm = this.fb.group({
        CustomerName: ['', Validators.required],
        ProductName: ['', Validators.required],
        ProductDesc: [''],
        OrderQuantity: ['', [Validators.required, Validators.pattern("^[0-9]*$")]],      
        OrderDate: ['',[Validators.required]],
        OrderDueDate: ['', Validators.required],
     });
    
    this.coId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.coId)) {
      console.log('Not a Number!');
      this.router.navigate(['/customer-order']);
    }
    else {
      this.dataService.getCustomerOrder(Number(this.coId))
        .subscribe(
          data => {
            if(data===null){
              console.log('customer-order not found!');
           
              this.apiResponse = 'Customer-Order Not Found!';
              this.responseColor = 'red';
            }
            else{
              this.apiResponse = '';
              this.responseColor = 'green';       
          
              this.coForm.setValue({
                CustomerName: data.customerName,
                ProductName: data.productName,
                ProductDesc: data.productDesc,
                OrderQuantity: data.orderQuantity,                
                OrderDate: new Date(Date.parse(data.orderDate)),
                OrderDueDate: new Date(Date.parse(data.orderDueDate)),
              });

              console.log(data);
            }
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          });
    }
  }

  get coFormControl() {
    return this.coForm.controls;
  }

  onSubmit(): void {
    this.submitted = true;
    if (this.coForm.valid) {
      
      this.coModel.customerName = this.coForm.value["CustomerName"];
      this.coModel.productName = this.coForm.value["ProductName"];
      this.coModel.productDesc = this.coForm.value["ProductDesc"];      
      this.coModel.orderQuantity = Number(this.coForm.value["OrderQuantity"]);
      // this.coModel.orderDate = new Date(this.coForm.value["OrderDate"].year + '/' + this.coForm.value["OrderDate"].month + '/' + this.coForm.value["OrderDate"].day);
      // this.coModel.orderDueDate = new Date(this.coForm.value["OrderDueDate"].year + '/' + this.coForm.value["OrderDueDate"].month + '/' + this.coForm.value["OrderDueDate"].day);
      this.coModel.orderDate = this.coForm.value["OrderDate"];
      this.coModel.orderDueDate = this.coForm.value["OrderDueDate"];
      this.coModel.customerOrderId = Number(this.coId);

      console.log(this.coModel);

      this.dataService.editCustomerOrder(this.coModel)
        .subscribe(
          response => {
            this.modelErrors = [];
            this.apiResponse = '';

            if (response.responseCode === 0) {              
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetCo();
              this.submitted = false;
              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/customer-order']);
              }, 2000);  
            }
            else {
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Customer-Order-Create');
            }
            else
              this.apiResponse = 'Error !';            
          }
        );
    }
    else {
      console.log('form in-valid!');
    }
  }
  
  resetCo(){
    this.coForm.reset();
    this.submitted = false;
  }

}

<div class="container">
    <div class="col-md-12 mx-auto">
        <div class="card">
            <div class="card-header componentHeader">
                <h4>
                    <div>
                        #{{coId}}) Customer-Order - Edit
                    </div>
                </h4>
                <h5 *ngIf="apiResponse">
                    <span [style.color]="responseColor">
                        {{apiResponse}}
                    </span>
                </h5>
            </div>
            <div class="card-body">
                <form class="form-co" 
                    [formGroup]="coForm" 
                    (ngSubmit)="onSubmit()">

                    <div class="row">
                        <div class="col-md-1 mx-auto"></div>
                        <div class="col-md-5 mx-auto">
                            <div class="form-group">
                                <label>Customer Name</label>
                                <input type="text" class="form-control " formControlName="CustomerName" />
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.CustomerName.touched || submitted) && coFormControl.CustomerName.errors?.required">
                                    Customer Name is required
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Product Name</label>
                                <input type="text" class="form-control " formControlName="ProductName" />
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.ProductName.touched || submitted) && coFormControl.ProductName.errors?.required">
                                    Product Name is required
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Product Desc</label>
                                <textarea type="text" 
                                    class="form-control" 
                                    formControlName="ProductDesc">
                                </textarea>
                            </div>
                        </div>
                        <div class="col-md-1 mx-auto"></div>
                        <div class="col-md-5 mx-auto">
                            <div class="form-group">
                                <label>Order Qty</label>
                                <input type="text" 
                                    class="form-control qtyField"
                                    formControlName="OrderQuantity" />
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.OrderQuantity.touched || submitted) && coFormControl.OrderQuantity.errors?.required">
                                    Order Qty is required
                                </div>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.OrderQuantity.touched || submitted) && coFormControl.OrderQuantity.errors?.pattern">
                                    Only Numbers are allowed
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <div class="input-group dateField">
                                    <input 
                                        formControlName="OrderDate" 
                                        type="text" 
                                        placeholder="Order-Date" 
                                        class="form-control" 
                                        bsDatepicker>                                   
                                </div>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.OrderDate.touched || submitted) && coFormControl.OrderDate.errors?.required">
                                    Order Date is required
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <div class="input-group dateField">
                                    <input 
                                        formControlName="OrderDueDate" 
                                        type="text" 
                                        placeholder="Order-Due-Date" 
                                        class="form-control" 
                                        bsDatepicker>
                                </div>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(coFormControl.OrderDueDate.touched || submitted) && coFormControl.OrderDueDate.errors?.required">
                                    Order Due Date is required
                                </div>
                            </div>                        
                        </div>
                    </div>

                  
                    <hr />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" class="btn btn-success">
                                    Edit Customer-Order
                                </button>
                            </div>
                            <div class="col-sm-6">
                                <button type="button" (click)="resetCo()" class="btn btn-primary cancelBtn">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
