// NgApp-WOT/src/app/work-order/work-order.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

import {NgbModal, ModalDismissReasons} from '@ng-bootstrap/ng-bootstrap';

import { CustomerOrderDetailsModalComponent } from './customer-order-details-modal/customer-order-details-modal.component';


@Component({
  selector: 'app-work-order',
  templateUrl: './work-order.component.html',
  styleUrls: ['./work-order.component.css']
})
export class WorkOrderComponent implements OnInit {

  term: string;
  
  wos: Array<any>;

  apiResponse = '';  
  responseColor = '';
  responseClass = '';
  
  page: number = 1;
  count: number = 0;
  tableSize: number = 3;
  tableSizes: any = [3, 6, 9, 12];

  coDetails = {};
  closeResult: string = '';

  constructor(private modalService: NgbModal, public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
    this.loadWos();  
  }

  onTableDataChange(event: any) {
    this.page = event;
    this.loadWos();
  }
  onTableSizeChange(event: any): void {
    this.tableSize = event.target.value;
    this.page = 1;
    this.loadWos();
  }

  loadWos(){
    this.dataService.allWorkOrders()
      .subscribe(
        data => {          
          console.log(data);

          this.wos = data;
          this.responseColor = 'green';
          this.apiResponse = 'Success!';
          this.responseClass = 'successResponse';

          console.log(this.wos);
        },
        error => {
          console.log(error);
          if (error.status == 401)            
            this.apiResponse = 'Un-Authorized !';
          else
            this.apiResponse = 'Error !';
          
          this.responseColor = 'red';
          this.responseClass = 'errorResponse';
          this.wos = [];      
      });
  }

  editWo(wo) {
    this.router.navigate(['/work-order-edit/'+ wo.workOrderId]);
  }

  removeWo(wo) {
    this.router.navigate(['/work-order-remove/'+ wo.workOrderId]);
  }
  
  createWo() {
    console.log('new work-order!');
    setTimeout(() => {
      this.router.navigate(['/work-order-create']);
    }, 500);
  }

  connectWithOperations(wo) {
    console.log("getting operations for wo : ", wo.workOrderId);
    setTimeout(() => {
      this.router.navigate(['/operation/'+wo.workOrderId]);
    }, 500);
  }

  getCustomerOrderDetails(coId) {
    console.log(coId);

    this.dataService.getCustomerOrderDetails(coId)
      .subscribe(
        data => {          
          if (data === "") {
            // data not found on server!
            this.coDetails = {};
          } else {
            console.log(data);
            this.coDetails=data;

            // CustomerOrderDetailsModalComponent is component name where modal is declare
            const modalRef = this.modalService.open(CustomerOrderDetailsModalComponent);
            modalRef.componentInstance.customerOrderDetails = data;
            modalRef.result.then((result) => {
              console.log(result);
            }).catch((error) => {
              console.log(error);
            });
          }
        },
        error => {
          console.log(error);
        }
      );
  }


}

<div class="container">

    <div class="mainHeader">Work-Orders [Operations]</div>
    <hr />
    <p></p>
    <div>
        <button 
            type="button" 
            (click)="createWo()" 
            class="btn btn-success">
                Create New Work-Order
        </button>
    </div>
    

    <div class="subHeaderWo">Work-Orders</div>
    <p></p>


    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">                
                <div class="card-body">
                    <div 
                        *ngIf="wos?.length>0; else noWos" 
                        class="container">

                        <div class="form-group">
                            <input 
                                type="text" 
                                class="searchControl form-control" 
                                placeholder="Search Work-Order"
                                [(ngModel)]="term">
                        </div>
                        <p></p>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Customer</th>
                                    <th>Start Date</th>
                                    <th>Status</th>
                                    <th>Notes-Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let wo of wos  | filter:term | paginate
                                        : {
                                            itemsPerPage: tableSize,
                                            currentPage: page,
                                            totalItems: count
                                        };
                                        let i = index
                                    ">
                                    <th scope="row">{{ wo.workOrderId }}</th>
                                    <td>
                                        <button 
                                            class="btn btn-link coDetailsBtn" 
                                            (click)="getCustomerOrderDetails(wo.customerOrderId)"
                                            type="button">
                                            [ {{wo.customerOrderId}} ] {{ wo.customerName }}
                                        </button>
                                    </td>
                                    <td>{{ wo.workOrderStartDate | date: "dd-MMM,yyyy" }}</td>
                                    <td>{{ wo.workOrderStatus }}</td>
                                    <td>
                                        <span *ngIf="wo.statusNote!=null && wo.statusNote.length>10; else fullDesc">
                                            {{wo.statusNote.substring(0,10)}}...
                                        </span>
                                        <ng-template #fullDesc>
                                            {{wo.statusNote}}
                                        </ng-template>
                                    </td>                                   
                                    <td>
                                        <div class="row">
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="editWo(wo)" class="btn btn-primary">
                                                    <i class="bi bi-pencil-square"></i>
                                                </button>
                                            </div>
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="removeWo(wo)" class="btn btn-danger">
                                                    <i class="bi bi-trash"></i>
                                                </button>
                                            </div>                                          
                                            <div class="col-8"></div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                            <pagination-controls previousLabel="Prev" nextLabel="Next"
                                (pageChange)="onTableDataChange($event)">
                            </pagination-controls>
                        </div>
                    </div>
                    <ng-template #noWos>
                        <div class="container">
                            <span class="noWos">
                                Work-Orders Not Found !
                            </span>
                        </div>
                    </ng-template>
                </div>
            </div>
        </div>
    </div>


    <!-- customer order details (bootstrap-modal)-->
    <button class="btn btn-lg btn-outline-primary" (click)="open(mymodal)">Open My Modal</button>
    <ng-template #mymodal let-modal>
        <div class="modal-header">
            <h4 class="modal-title" id="modal-basic-title">Bootstrap Modal</h4>
            <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">
            This is example from ItSolutionStuff.com
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-dark" (click)="modal.close('Save click')">Ok</button>
        </div>
    </ng-template>
</div>

// reactapp-wot/src/components/Work_Order/Work_Order.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AuthService from "../../services/auth.service";
import CustomerOrderService from "../../services/customerOrder.service";
import WorkOrderService from "../../services/workOrder.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import { Modal, Button } from "react-bootstrap";

import Moment from "moment";

import {
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../services/local.service";

const Work_Order = () => {
  let navigate = useNavigate();

  const [wos, setWos] = useState([]);
  const [co, setCo] = useState({});

  // bootstrap modal
  const [isOpen, setIsOpen] = useState(false);
  const openModal = () => setIsOpen(true);
  const closeModal = () => setIsOpen(false);

  const getAllWorkOrders = () => {
    WorkOrderService.allWorkOrders()
      .then((response) => {
        console.log(response.data);
        setWos(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        }
      });
  };

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getAllWorkOrders();
  }, []);

  const displayDate = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return Moment(cell).format("DD-MMM-YYYY");
    }
  };

  const displayNote = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return cell;
    }
  };

  const displayWoStatus = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return getWorkOrderStatus(cell);
    }
  };

  const displayActionBtn = (cell, row) => {
    return (
      <div>
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editWo(e, row.workOrderId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>
        &nbsp;
        <Button
          className="btn btn-danger"
          type="button"
          onClick={(e) => removeWo(e, row.workOrderId)}
        >
          <i className="bi bi-trash"></i>
        </Button>
        &nbsp;
        <Button
          className="btn btn-success"
          type="button"
          onClick={(e) => connectWithOperations(e, row.workOrderId)}
        >
          <i className="bi-list-task"></i>
        </Button>
      </div>
    );
  };

  const getCustomerOrderDetails = (e, coid) => {
    console.log("getting customer order info #", coid);

    WorkOrderService.getCustomerOrderDetails(coid)
      .then((response) => {
        if (response.data === "") {
          // data not found on server!
          setCo(null);
        } else {
          console.log(response.data);

          setCo(response.data);
        }
        openModal();
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const displayCustomerOrder = (cell, row) => {
    return (
      <div>
        <button
          className="btn btn-link"
          type="button"
          onClick={(e) => getCustomerOrderDetails(e, row.customerOrderId)}
        >
          {cell}
        </button>
      </div>
    );
  };
  const columns = [
    {
      dataField: "workOrderId",
      text: "#",
      sort: true,
    },
    {
      dataField: "customer",
      text: "Customer",
      sort: true,
      formatter: (cell, row) => displayCustomerOrder(cell, row),
    },
    {
      dataField: "workOrderStartDate",
      text: "Start Date",
      sort: true,
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "workOrderStatus",
      text: "Status",
      formatter: (cell) => displayWoStatus(cell),
    },
    {
      dataField: "statusNote",
      text: "Notes",
      formatter: (cell) => displayNote(cell),
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const createNewWo = () => {
    navigate("/work-order-create");
  };
  const editWo = (e, woId) => {
    console.log("edit wo : ", woId);
    navigate("/work-order-edit/" + woId);
  };
  const removeWo = (e, woId) => {
    console.log("remove wo : ", woId);
    navigate("/work-order-remove/" + woId);
  };
  const connectWithOperations = (e, woId) => {
    console.log("getting operations for wo : ", woId);
    navigate("/operation/" + woId);
  };

  return (
    <div className="container">
      <div className="mainHeader">Work-Orders [Operations]</div>
      <hr />
      <Button
        className="btn btn-success"
        type="button"
        onClick={(e) => createNewWo(e)}
      >
        Create New Work-Order
      </Button>
      <p></p>

      <div className="subHeaderWo">Work-Orders</div>
      <p></p>
      {wos && wos.length > 0 ? (
        <BootstrapTable
          bootstrap4
          keyField="workOrderId"
          data={wos}
          columns={columns}
          pagination={paginationFactory({ sizePerPage: 20 })}
          filter={filterFactory()}
        />
      ) : (
        <div className="noWos">No Work-Orders!</div>
      )}

      <Modal show={isOpen} onHide={closeModal}>
        <Modal.Header closeButton>
          <Modal.Title>Customer Order Details!!</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {co ? (
            <div className="card">
              <div className="card-header">
                <span className="coHeader">
                  Customer Order # {co.customerOrderId}
                </span>
              </div>
              <div className="card-body">
                <h4>
                  <span className="coLabel">Customer Name :</span>{" "}
                  {co.customerName}
                </h4>
                <h5>
                  <span className="coLabel">Product Name : </span>
                  {co.productName}
                </h5>
                <h6>
                  <span className="coLabel">Product Desc : </span>
                  {co.productDesc}
                </h6>
                <h6>
                  <span className="coLabel">Order QTY #</span>{" "}
                  <span className="coQty">{co.orderQuantity}</span>
                </h6>
                <h6>
                  <span className="coLabel">Order Date #</span>{" "}
                  {Moment(co.orderDate).format("DD-MMM-YYYY")}
                </h6>
                <h5>
                  <span className="coLabel">Order Due Date #</span>{" "}
                  <span className="coDueDate">
                    {Moment(co.orderDueDate).format("DD-MMM-YYYY")}
                  </span>
                </h5>
              </div>
            </div>
          ) : (
            <div className="card">
              <div className="card-header">Customer Order # N/A</div>
              <div className="card-body noCo">
                Customer Order Details Not Found !
              </div>
            </div>
          )}
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={closeModal}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default Work_Order;
