// reactapp-wot/src/components/WorkOrder_Create/WorkOrder_Create.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import CustomerOrderService from "../../services/customerOrder.service";
import WorkOrderService from "../../services/workOrder.service";

import { useNavigate } from "react-router";

import Moment from "moment";

import { getWorkOrderStatusToDisplay } from "../../services/local.service";

const WorkOrder_Create = () => {
  let navigate = useNavigate();

  const [customerOrders, setCustomerOrders] = useState([]);
  const [workOrderStatusCollection, setWorkOrderStatusCollection] = useState(
    []
  );

  const [modelErrors, setModelErrors] = useState([]);

  const [woCreateResponse, setWoCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      setWorkOrderStatusCollection(getWorkOrderStatusToDisplay());
      getCustomerOrders();
    }
  }, []);

  const getCustomerOrders = () => {
    WorkOrderService.getCustomerOrders()
      .then((response) => {
        console.log(response.data);

        setCustomerOrders(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const findFormErrors = () => {
    const { customerOrderId, workOrderStartDate, workOrderStatus, statusNote } =
      form;
    const newErrors = {};

    if (!customerOrderId || customerOrderId === "")
      newErrors.customerOrderId = "Customer-Order is Required!";
    if (!workOrderStatus || workOrderStatus === "")
      newErrors.workOrderStatus = "Work-Order Status is Required!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var oDate = Moment(form.workOrderStartDate);
      var oCheck = oDate.isValid();
      if (oCheck) {
        var woModel = {
          customerOrderId: form.customerOrderId,
          workOrderStartDate: form.workOrderStartDate,
          workOrderStatus: form.workOrderStatus,
          statusNote: form.statusNote,
        };

        console.log(woModel);
        // api call
        WorkOrderService.createWorkOrder(woModel)
          .then((response) => {
            setModelErrors([]);
            setWoCreateResponse({});
            console.log(response.data);

            var woCreateResponse = {
              responseCode: response.data.responseCode,
              responseMessage: response.data.responseMessage,
            };
            if (response.data.responseCode === 0) {
              resetForm();
              setWoCreateResponse(woCreateResponse);

              setTimeout(() => {
                navigate("/work-order");
              }, 3000);
            } else if (response.data.responseCode === -1) {
              setWoCreateResponse(woCreateResponse);
            }
          })
          .catch((error) => {
            console.log(error);
            setModelErrors([]);
            setWoCreateResponse({});
            // 400
            // ModelState
            if (error.response.status === 400) {
              console.log("400 !");
              var modelErrors = handleModelState(error);
              setModelErrors(modelErrors);
            }
          });
      } else {
        console.log("Invalid Date(s) !");
        var woCreateResponse = {
          responseCode: -1,
          responseMessage: "Invalid Date !",
        };
        setWoCreateResponse(woCreateResponse);
        setModelErrors([]);
      }
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setWoCreateResponse({});
    setModelErrors([]);
  };

  const renderOptionsForCustomerOrders = () => {
    return customerOrders.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.text}>
          {dt.text}
        </option>
      );
    });
  };
  const renderOptionsForWorkOrderStatus = () => {
    return workOrderStatusCollection.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.woStatus}>
          {dt.woStatus}
        </option>
      );
    });
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-9 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Create New Work-Order</h3>
                <p></p>{" "}
                {woCreateResponse && woCreateResponse.responseCode === -1 ? (
                  <span className="woCreateError">
                    {woCreateResponse.responseMessage}
                  </span>
                ) : (
                  <span className="woCreateSuccess">
                    {woCreateResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="customerOrderId">
                        <Form.Label>Customer-Order</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.customerOrderId}
                          onChange={(e) => {
                            setField("customerOrderId", e.target.value);
                          }}
                        >
                          <option value="">Select Customer-Order</option>
                          {renderOptionsForCustomerOrders()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.customerOrderId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="workOrderStartDate">
                        <Form.Label>Work-Order Start Date</Form.Label>
                        <Form.Control
                          type="date"
                          name="workOrderStartDate"
                          placeholder="Work-Order Start Date"
                          isInvalid={!!errors.workOrderStartDate}
                          onChange={(e) =>
                            setField("workOrderStartDate", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.workOrderStartDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="workOrderStatus">
                        <Form.Label>Work-Order Status</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.workOrderStatus}
                          onChange={(e) => {
                            setField("workOrderStatus", e.target.value);
                          }}
                        >
                          <option value="">Select Work-Order Status</option>
                          {renderOptionsForWorkOrderStatus()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.workOrderStatus}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="statusNote">
                        <Form.Label>Note</Form.Label>
                        <Form.Control
                          as="textarea"
                          rows="3"
                          isInvalid={!!errors.statusNote}
                          onChange={(e) =>
                            setField("statusNote", e.target.value)
                          }
                        />
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Create Work-Order
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default WorkOrder_Create;

// NgApp-WOT/src/app/work-order-create/work-order-create.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { DataService } from '../services/data.service';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-work-order-create',
  templateUrl: './work-order-create.component.html',
  styleUrls: ['./work-order-create.component.css']
})
export class WorkOrderCreateComponent implements OnInit {

  customerOrders: Array<any>;
  workOrderStatusCollection: Array<any>;

  woForm: FormGroup;
  submitted = false;
  woModel = {
    customerOrderId: '',
    workOrderStartDate: new Date(),
    workOrderStatus: 0,
    statusNote: '',
  };

  apiResponse = '';  
  responseColor = '';
  modelErrors = [];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
    this.woForm = this.fb.group({
      CustomerOrderId: ['', Validators.required],
      WorkOrderStartDate: ['', Validators.required],
      WorkOrderStatus: ['', [Validators.required]],      
      StatusNote: [''],
    });

    this.getCustomerOrders();
    this.workOrderStatusCollection = this.localDataService.getWorkOrderStatusToDisplay();
  }

  getCustomerOrders() {
    this.dataService.getCustomerOrders()
      .subscribe(
        data => {
          this.customerOrders = data;
        },
        error => {
          console.log(error);
        }
      );
  }
  
  get woFormControl() {
    return this.woForm.controls;
  }

  resetWo() {    
    this.woForm.reset();
    this.submitted = false;
  } 

  onSubmit(): void {

    this.submitted = true;

    if (this.woForm.valid) {
      console.log('form valid!');    

      this.woModel.customerOrderId = this.woForm.value["CustomerOrderId"];
      this.woModel.workOrderStatus = this.woForm.value["WorkOrderStatus"];
      this.woModel.statusNote = this.woForm.value["StatusNote"];
      this.woModel.workOrderStartDate = new Date(this.woForm.value["WorkOrderStartDate"].year + '/' + this.woForm.value["WorkOrderStartDate"].month + '/' + this.woForm.value["WorkOrderStartDate"].day);
     
      console.log(this.woModel);

      // check for server side model errors
      // this.woModel.customerOrderId = '';
      this.dataService.createWorkOrder(this.woModel)
        .subscribe(
          response => {
            this.modelErrors = [];
            this.apiResponse = '';

            console.log(response);

            if(response.responseCode===0){
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetWo();
              this.submitted = false;

              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/work-order']);
              }, 2000);  
              
            }
            else{
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            // console.log(error);
            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Work-Order-Create');
            }
            else
              this.apiResponse = 'Error !';            
          }
        );
    }
    else {
      console.log('form in-valid!');
    }
  } 

}

<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto">
            <div class="card">
                <div class="card-header componentHeader">
                    <h4>
                        <div>
                            Create New Work-Order
                        </div>
                    </h4>
                    <h5 *ngIf="apiResponse">
                        <p></p>
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                    </h5>
                    <h5 *ngIf="modelErrors.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of modelErrors">
                                {{ error }}
                            </li>
                        </ul>
                    </h5>
                </div>

                <div class="card-body">
                    <form class="form-wo" 
                        [formGroup]="woForm" 
                        (ngSubmit)="onSubmit()">

                        <div class="row">
                            <div class="col-md-1 mx-auto"></div>
                            <div class="col-md-10 mx-auto">
                                <div class="form-group">
                                    <label>Customer</label>
                                    <select 
                                        class="form-control" 
                                        formControlName="CustomerOrderId">
                                        <option value="">Choose Customer</option>
                                        <option value={{co.value}} *ngFor="let co of customerOrders">
                                            {{co.text}}
                                        </option>
                                    </select>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(woFormControl.CustomerOrderId.touched || submitted) && woFormControl.CustomerOrderId.errors?.required">
                                        Customer is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Work-Order Status</label>
                                    <select class="form-control" 
                                        formControlName="WorkOrderStatus">
                                        <option value="">Choose Work-Order Status</option>
                                        <option value={{wo.value}} *ngFor="let wo of workOrderStatusCollection">
                                            {{wo.woStatus}}
                                        </option>
                                    </select>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(woFormControl.WorkOrderStatus.touched || submitted) && woFormControl.WorkOrderStatus.errors?.required">
                                        Work-Order Status is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Work-Order Start Date</label>
                                    <div class="input-group dateField">
                                        <input type="date" 
                                            class="form-control" 
                                            placeholder="yyyy-mm-dd" 
                                            name="workOrderStartDate"
                                            formControlName="WorkOrderStartDate" 
                                            ngbDatepicker #d="ngbDatepicker">
                                    </div>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(woFormControl.WorkOrderStartDate.touched || submitted) && woFormControl.WorkOrderStartDate.errors?.required">
                                        Work-Order Start Date is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Status Note</label>
                                    <textarea 
                                        type="text" 
                                        class="form-control" 
                                        formControlName="StatusNote">
                                    </textarea>
                                </div>
                            </div>   
                            <div class="col-md-1 mx-auto"></div>
                        </div>

                        <hr />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-5">
                                    <button type="submit" class="btn btn-success">
                                        New Work-Order
                                    </button>
                                </div>
                                <div class="col-sm-3"></div>
                                <div class="col-sm-4 ">
                                    <button type="button" 
                                        (click)="resetWo()" 
                                        class="btn btn-primary cancelBtn">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
