// NgApp-WOT/src/app/operation-log/operation-log.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-operation-log',
  templateUrl: './operation-log.component.html',
  styleUrls: ['./operation-log.component.css']
})
export class OperationLogComponent implements OnInit {

  opId: string;
  woId: number;
  opLog;
  
  apiError = '';  

  page: number = 1;
  count: number = 0;
  tableSize: number = 10;
  tableSizes: any = [3, 6, 9, 12];

  
  constructor(public localDataService: LocalDataService, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {
    this.loadOpLog();     
  }
  onTableDataChange(event: any) {
    this.page = event;
    this.loadOpLog();
  }
  onTableSizeChange(event: any): void {
    this.tableSize = event.target.value;
    this.page = 1;
    this.loadOpLog();
  }

  goBack() {
    this.router.navigate(['/operation/'+this.woId]);
  }
  
  loadOpLog() {
    
    this.woId = this.localDataService.getWorkOrderId();
    if (this.woId===null || isNaN(+this.woId)) {
      console.log('Invalid Work-Order!');
      this.router.navigate(['/work-order']);
    }

    this.opId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.opId)) {
      console.log('Not a Number!');
      this.router.navigate(['/work-order']);
    }
    else {
      this.dataService.getOperationLogData(Number(this.opId))
        .subscribe(
          data => {
            console.log(data);
            this.opLog = data;
          },
          error => {
            console.log(error);
            if (error.status == 401)            
              this.apiError = 'Un-Authorized !';
            else
              this.apiError = error.error;
            
            this.opLog = {};     
          });
    }
  }

}

<div class="container">
    <div class="mainHeader">Operation-Log</div>
    <hr />


    <div class="row">
        <div class="col-md-10 mx-auto">
            <div *ngIf="opLog" class="subHeader">
                Operation # {{opId}}
                <br />
                Operation Number # {{localDataService.getOperationNumber(opLog.operationNumber)}}
                <br />
                Work-Order # {{opLog.workOrderId}}
            </div>

            <div *ngIf="apiError">
                <div class="apiError">{{apiError}}</div>
            </div>
        </div>
        <div class="col-md-2 mx-auto">
            <button type="button" (click)="goBack()" class="btn btn-primary cancelBtn">
                <i class="bi bi-arrow-return-left"></i> Back
            </button>
        </div>

    </div>

    <p></p>
    <div *ngIf="(opLog && opLog.operationHistory?.length>0); else noOps">
        <div class="operationHeader">
            Operation-Log-Data
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Operator</th>
                    <th>Start Time</th>
                    <th>Pause Time</th>
                    <th>Cycle Time</th>
                    <th>QTY-Done</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let op of opLog.operationHistory  | paginate
                                                : {
                                                    itemsPerPage: tableSize,
                                                    currentPage: page,
                                                    totalItems: count
                                                };
                                                let i = index
                                            ">              
                    <td>{{op.operatorName}} [{{op.operatorId}}]</td>
                    <td>{{op.opStartRunTime | date: "dd-MMM, hh:mm a" }}</td>
                    <td>{{op.opPauseRunTime | date: "dd-MMM, hh:mm a" }}</td>
                    <td>{{op.cycleTime}}</td>
                    <td>{{op.qtyDone}}</td>
                </tr>
            </tbody>
        </table>
        <div class="d-flex justify-content-center">
            <pagination-controls previousLabel="Prev" nextLabel="Next" (pageChange)="onTableDataChange($event)">
            </pagination-controls>
        </div>
    </div>
    <ng-template #noOps>
        <div class="noOps">
            No Operation-History!
        </div>        
    </ng-template>
</div>

// reactapp-wot/src/components/OperationLog/OperationLog.jsx
import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import "./style.css";
import AuthService from "../../services/auth.service";
import {
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../services/local.service";
import OperationService from "../../services/operation.service";
import { useNavigate } from "react-router-dom";

import { Table, Button } from "react-bootstrap";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Moment from "moment";

const OperationLog = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [opLog, setOpLog] = useState([]);
  const [apiError, setApiError] = useState("");

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else GetOperationLogData(id);
  }, []);

  const GetOperationLogData = (id) => {
    OperationService.getOperationLogData(id)
      .then((response) => {
        console.log(response.data);

        // add index column to response.data.operationHistory
        var index = 1;
        response.data.operationHistory.forEach(function (element) {
          element.id = index++;
        });
        console.log(response.data.operationHistory);

        setOpLog(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        } else if (e.response.status === 400) {
          setApiError(e.response.data);
        }
      });
  };

  const displayDate = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return Moment(cell).format("DD-MMM, h:mm a");
    }
  };

  const displayOperator = (cell, row) => {
    return row.operatorName + " [" + cell + "]";
  };

  const columns = [
    {
      dataField: "id",
      text: "#",
      sort: true,
    },
    {
      dataField: "cycleTime",
      text: "Cycle Time",
      sort: true,
    },
    {
      dataField: "opStartRunTime",
      text: "Start Time",
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "opPauseRunTime",
      text: "Pause Time",
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "operatorId",
      text: "Operator",
      formatter: (cell, row) => displayOperator(cell, row),
    },
    {
      dataField: "qtyDone",
      text: "QTY-Done",
    },
  ];

  const goBack = (e) => {
    navigate("/operation/" + opLog.workOrderId);
  };

  return (
    <div className="container">
      <div className="mainHeader">Operation-Log</div>
      <hr />

      <div className="row">
        <div className="col-md-10 mx-auto">
          <div className="subHeader">
            Operation # {id}
            <br />
            Operation Number # {getOperationNumber(opLog.operationNumber)}
            <br />
            Work-Order # {opLog.workOrderId}
          </div>
          {apiError && <div className="apiError">{apiError}</div>}

          {opLog.operationHistory && opLog.operationHistory.length > 0 && (
            <div className="operationHeader">Operation-Log-Data</div>
          )}
        </div>

        <div className="col-md-2 mx-auto">
          {opLog && opLog.workOrderId ? (
            <Button
              className="btn btn-primary"
              type="button"
              onClick={(e) => goBack(e)}
            >
              <i className="bi bi-arrow-return-left"></i> Back
            </Button>
          ) : (
            <span></span>
          )}
        </div>
      </div>

      <p></p>

      {opLog.operationHistory && opLog.operationHistory.length > 0 ? (
        <BootstrapTable
          bootstrap4
          keyField="id"
          data={opLog.operationHistory}
          columns={columns}
          pagination={paginationFactory({ sizePerPage: 20 })}
          filter={filterFactory()}
        />
      ) : (
        <div className="noOps">No Operation-History!</div>
      )}
    </div>
  );
};

export default OperationLog;
