// reactapp-wot/src/components/CustomerOrder_Create/CustomerOrder_Create.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import CustomerOrderService from "../../services/customerOrder.service";

import { useNavigate } from "react-router";

const CustomerOrder_Create = () => {
  let navigate = useNavigate();

  const [modelErrors, setModelErrors] = useState([]);

  const [coCreateResponse, setCoCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
  }, []);

  // reset form
  // form reference
  const formRef = useRef(null);

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const {
      customerName,
      productName,
      productDesc,
      orderQty,
      orderDate,
      orderDueDate,
    } = form;
    const newErrors = {};

    if (!customerName || customerName === "")
      newErrors.customerName = "Customer Name is Required!";

    if (!productName || productName === "")
      newErrors.productName = "Product Name is Required!";

    if (!productDesc || productDesc === "")
      newErrors.productDesc = "Product Desc is Required!";

    if (!orderQty || orderQty === "")
      newErrors.orderQty = "Order Qty is Required!";
    else {
      if (!checkForNumbersOnly(orderQty))
        newErrors.orderQty = "Only Numbers are Allowed!";
    }

    if (!orderDate || orderDate === "")
      newErrors.orderDate = "Order Date is Required!";

    if (!orderDueDate || orderDueDate === "")
      newErrors.orderDueDate = "Order Due Date is Required!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var coModel = {
        customerName: form.customerName,
        productName: form.productName,
        productDesc: form.productDesc,
        orderQuantity: parseInt(form.orderQty),
        orderDate: form.orderDate,
        orderDueDate: form.orderDueDate,
      };

      console.log(coModel);

      // api call
      CustomerOrderService.createCustomerOrder(coModel)
        .then((response) => {
          setModelErrors([]);
          setCoCreateResponse({});
          console.log(response.data);
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setCoCreateResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);

            console.log(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setCoCreateResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-9 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Create New Customer-Order</h3>
                <p></p>{" "}
                {coCreateResponse && coCreateResponse.responseCode === -1 ? (
                  <span className="coCreateError">
                    {coCreateResponse.responseMessage}
                  </span>
                ) : (
                  <span className="coCreateSuccess">
                    {coCreateResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="customerName">
                        <Form.Label>Customer Name</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.customerName}
                          onChange={(e) =>
                            setField("customerName", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.customerName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="productName">
                        <Form.Label>Product Name</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.productName}
                          onChange={(e) =>
                            setField("productName", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.productName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="productDesc">
                        <Form.Label>Product Desc</Form.Label>
                        <Form.Control
                          as="textarea"
                          rows="3"
                          isInvalid={!!errors.productDesc}
                          onChange={(e) =>
                            setField("productDesc", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.productDesc}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-1 mx-auto"></div>
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="orderQty">
                        <Form.Label>Order Qty</Form.Label>
                        <Form.Control
                          className="qtyDisplay"
                          type="text"
                          isInvalid={!!errors.orderQty}
                          onChange={(e) => setField("orderQty", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderQty}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="orderDate">
                        <Form.Label>Order Date</Form.Label>
                        <Form.Control
                          type="date"
                          name="orderDate"
                          placeholder="Order Date"
                          isInvalid={!!errors.orderDate}
                          onChange={(e) =>
                            setField("orderDate", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="orderDueDate">
                        <Form.Label>Order Due Date</Form.Label>
                        <Form.Control
                          type="date"
                          name="orderDueDate"
                          placeholder="Order Due Date"
                          isInvalid={!!errors.orderDueDate}
                          onChange={(e) =>
                            setField("orderDueDate", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.orderDueDate}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Create Customer-Order
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default CustomerOrder_Create;

// NgApp-WOT/src/app/customer-order-create/customer-order-create.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { DataService } from '../services/data.service';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-customer-order-create',
  templateUrl: './customer-order-create.component.html',
  styleUrls: ['./customer-order-create.component.css']
})
export class CustomerOrderCreateComponent implements OnInit {

  coForm: FormGroup;
  submitted = false;
  coModel = {
    customerName: '',
    productName: '',
    productDesc: '',
    orderQuantity: 0,
    orderDate: new Date(),
    orderDueDate: new Date(),
  };

  apiResponse = '';  
  responseColor = '';
  modelErrors = [];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
    this.coForm = this.fb.group({
      CustomerName: ['', Validators.required],
      ProductName: ['', Validators.required],
      ProductDesc: [''],
      OrderQuantity: ['', [Validators.required, Validators.pattern("^[0-9]*$")]],      
      OrderDate: ['',[Validators.required]],
      OrderDueDate: ['', Validators.required],
    });
  }

  get coFormControl() {
    return this.coForm.controls;
  }

  resetCo() {    
    this.coForm.reset();
    this.submitted = false;
  }

  checkForNumbersOnly(newVal) {
    /*
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal))
      console.log('ok');
    else
      console.log('Only Numbers Allowed !!!');
    */
  }

  onSubmit(): void {

    this.submitted = true;

    if (this.coForm.valid) {
      this.coModel.customerName = this.coForm.value["CustomerName"];
      this.coModel.productName = this.coForm.value["ProductName"];
      this.coModel.productDesc = this.coForm.value["ProductDesc"];
      this.coModel.orderQuantity = Number(this.coForm.value["OrderQuantity"]);
      this.coModel.orderDate = new Date(this.coForm.value["OrderDate"].year + '/' + this.coForm.value["OrderDate"].month + '/' + this.coForm.value["OrderDate"].day);
      this.coModel.orderDueDate = new Date(this.coForm.value["OrderDueDate"].year + '/' + this.coForm.value["OrderDueDate"].month + '/' + this.coForm.value["OrderDueDate"].day);
     
      console.log(this.coModel);
            
      this.dataService.createCustomerOrder(this.coModel)
        .subscribe(
          response => {
            this.modelErrors = [];
            this.apiResponse = '';

            console.log(response);

            if(response.responseCode==0){
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetCo();
              this.submitted = false;

              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/customer-order']);
              }, 2000);  
              
            }
            else{
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            // console.log(error);
            this.modelErrors = [];
            this.apiResponse = '';
            this.responseColor = 'red';

            if (error.status === 401)            
              this.apiResponse = 'Un-Authorized !';
            else if (error.status === 400) {
              this.apiResponse = '';
              this.modelErrors = this.localDataService.display400andEx(error, 'Customer-Order-Create');
            }
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
    }
    else {
      console.log('form in-valid!');
    }
  } 
}

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header componentHeader">
                    <h4>
                        <div>
                            Create New Customer-Order
                        </div>
                    </h4>
                    <h5 *ngIf="apiResponse">
                        <p></p>
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                    </h5>
                    <h5 *ngIf="modelErrors.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of modelErrors">
                                {{ error }}
                            </li>
                        </ul>
                    </h5>
                </div>

                <div class="card-body">
                    <form class="form-co" 
                        [formGroup]="coForm" 
                        (ngSubmit)="onSubmit()">

                        <div class="row">
                            <div class="col-md-1 mx-auto"></div>
                            <div class="col-md-5 mx-auto">
                                <div class="form-group">
                                    <label>Customer Name</label>
                                    <input type="text" class="form-control " formControlName="CustomerName" />
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.CustomerName.touched || submitted) && coFormControl.CustomerName.errors?.required">
                                        Customer Name is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Product Name</label>
                                    <input type="text" class="form-control " formControlName="ProductName" />
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.ProductName.touched || submitted) && coFormControl.ProductName.errors?.required">
                                        Product Name is required
                                    </div>
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <label>Product Desc</label>
                                    <textarea type="text" 
                                        class="form-control" 
                                        formControlName="ProductDesc">
                                    </textarea>
                                </div>
                            </div>
                            <div class="col-md-1 mx-auto"></div>
                            <div class="col-md-5 mx-auto">
                                <div class="form-group">
                                    <label>Order Qty</label>
                                    <input type="text" 
                                        (ngModelChange)="checkForNumbersOnly($event)" 
                                        class="form-control qtyField"
                                        formControlName="OrderQuantity" />
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.OrderQuantity.touched || submitted) && coFormControl.OrderQuantity.errors?.required">
                                        Order Qty is required
                                    </div>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.OrderQuantity.touched || submitted) && coFormControl.OrderQuantity.errors?.pattern">
                                        Only Numbers are allowed
                                    </div>                                
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <div class="input-group dateField">
                                        <input  
                                            type="date"                                       
                                            class="form-control" 
                                            placeholder="Order-Date yyyy-mm-dd" 
                                            name="orderDate" 
                                            formControlName="OrderDate"
                                            ngbDatepicker
                                            #d="ngbDatepicker">                                      
                                    </div>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.OrderDate.touched || submitted) && coFormControl.OrderDate.errors?.required">
                                        Order Date is required
                                    </div>  
                                </div>
                                <p></p>
                                <div class="form-group">
                                    <div class="input-group dateField">
                                        <input class="form-control" 
                                            type="date"                                       
                                            placeholder="Order-Due-Date yyyy-mm-dd" 
                                            name="orderDueDate" 
                                            formControlName="OrderDueDate"
                                            ngbDatepicker #dd="ngbDatepicker">                                     
                                    </div>
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(coFormControl.OrderDueDate.touched || submitted) && coFormControl.OrderDueDate.errors?.required">
                                        Order Due Date is required
                                    </div>
                                </div>

                            </div>                            
                        </div>

                 
                        <hr />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-5">
                                    <button type="submit" 
                                        class="btn btn-success">
                                        New Customer-Order
                                    </button>
                                </div>
                                <div class="col-sm-3"></div>
                                <div class="col-sm-4 ">
                                    <button type="button" 
                                        (click)="resetCo()" 
                                        class="btn btn-primary cancelBtn">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
