// NgApp-WOT/src/app/operation/operation.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { LocalDataService } from '../services/local-data.service';

import {NgbModal, ModalDismissReasons} from '@ng-bootstrap/ng-bootstrap';

import { XferHistoryComponent } from '../xfer-history/xfer-history.component';;

@Component({
  selector: 'app-operation',
  templateUrl: './operation.component.html',
  styleUrls: ['./operation.component.css']
})
export class OperationComponent implements OnInit {

  woId: string;
  ops: Array<any>;

  apiResponse = '';  
  responseColor = '';
  responseClass = '';

  page: number = 1;
  count: number = 0;
  tableSize: number = 10;
  tableSizes: any = [3, 6, 9, 12];

  
  constructor(private modalService: NgbModal, public localDataService: LocalDataService, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {
    this.loadOps();     
  }
  onTableDataChange(event: any) {
    this.page = event;
    this.loadOps();
  }
  onTableSizeChange(event: any): void {
    this.tableSize = event.target.value;
    this.page = 1;
    this.loadOps();
  }

  loadOps() {
    this.woId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.woId)) {
      console.log('Not a Number!');
      this.router.navigate(['/work-order']);
    }
    else {
      this.dataService.getAllWorkOrderOperations(Number(this.woId))
        .subscribe(
          data => {
            this.ops = data;
            console.log(this.ops);
          },
          error => {
            console.log(error);
            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
            this.responseClass = 'errorResponse';
            this.ops = [];     
          });
    }
  }

  editOp(op) {
    console.log('editing operation :', op);
    this.localDataService.setWorkOrderId(this.woId);
    this.router.navigate(['/operation-edit/'+op.operationId]);
  }

  xferParts(op) {
    console.log('xfer parts for operation :', op.operationId);
    this.localDataService.setWorkOrderId(this.woId);
    this.router.navigate(['/xfer-parts/'+op.operationId]);
  }
  
  createOp() {
    this.localDataService.setWorkOrderId(this.woId);
    this.router.navigate(['/operation-create']);
  }

  getOpLog(opId) {
    console.log('getting operation log : ', opId);
  }

  getPartHistory(op) {
    console.log('getting part history for operation : ', op.operationId);

    this.dataService.getPartHistory(op.operationId)
      .subscribe(
        data => {          
            // xfer-history-component where modal is declare
            const modalRef = this.modalService.open(XferHistoryComponent);
            modalRef.componentInstance.partHistoryData = data;
            modalRef.result.then((result) => {
              console.log(result);
            }).catch((error) => {
              console.log(error);
            });
        },
        error => {
          console.log(error);
          if (error.status === 400) {
            console.log(error.error);

            // xfer-history-component where modal is declare
            const modalRef = this.modalService.open(XferHistoryComponent);
            modalRef.componentInstance.apiError = error.error;
            modalRef.result.then((result) => {
              console.log(result);
            }).catch((error) => {
              console.log(error);
            });
          }
        }
      );
  }

}

<div class="container">

    <div class="mainHeader">Work-Orders [Operations]</div>
    <hr />
    <p></p>

    <div class="row">
        <div class="col-md-3 mx-auto">
            <button type="button" (click)="createOp()" class="btn btn-success">
                Create New Operation
            </button>
        </div>
        <div class="col-md-6 mx-auto">
            <div class="subHeaderOp">
                Work-Order # {{woId}}
                <br />
                Operations
            </div>
        </div>
        <div class="col-md-3 mx-auto"></div>
    </div>
    <p></p>

    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-body">
                    <div *ngIf="ops?.length>0; else noOps" 
                        class="container">
                        <p></p>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Details</th>
                                    <th>Status</th>
                                    <th>Start Date</th>
                                    <th>QTY-Done</th>
                                    <th>QTY-Required</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let op of ops  | paginate
                                        : {
                                            itemsPerPage: tableSize,
                                            currentPage: page,
                                            totalItems: count
                                        };
                                        let i = index
                                    ">
                                    <th scope="row">
                                        <button 
                                            type="button" 
                                            (click)="getOpLog(op.operationId)" 
                                            class="btn btn-info">
                                            <i class="bi-binoculars"></i>
                                        </button>
                                        {{ op.operationId }}
                                    </th>
                                    <td>
                                        <span *ngIf="op.details!==null && op.details.length>10; else fullDesc">
                                            {{op.details.substring(0,10)}}...
                                        </span>
                                      
                                        <ng-template #fullDesc>
                                            <span *ngIf="(op.details==='' || op.details===null); fullContent">
                                                N/A
                                            </span>
                                            <ng-template #fullContent>
                                                {{op.details}}
                                            </ng-template>
                                        </ng-template>
                                    </td>
                                    <td>{{ localDataService.getOperationStatus(op.operationStatus) }}</td>                                   
                                    <td>
                                        {{ op.operationStartDate | date: "dd-MMM,yyyy" }}
                                    </td>
                                    <td>{{ op.opQTYDone}}</td>
                                    <td>{{ op.opQTYRequired}}</td>
                                    <td>
                                        <div class="row">
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="editOp(op)" class="btn btn-primary">
                                                    <i class="bi bi-pencil-square"></i>
                                                </button>
                                            </div>
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="xferParts(op)" class="btn btn-warning">
                                                    <i class="bi-arrows-move"></i>
                                                </button>
                                            </div>   
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="getPartHistory(op)" 
                                                    class="btn btn-success">
                                                    <i class="bi-clock-history"></i>
                                                </button>
                                            </div>
                                            <div class="col-8"></div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                            <pagination-controls previousLabel="Prev" nextLabel="Next"
                                (pageChange)="onTableDataChange($event)">
                            </pagination-controls>
                        </div>
                    </div>
                    <ng-template #noOps>
                        <div class="container">
                            <span class="noOps">
                                Operations Not Found !
                            </span>
                        </div>
                    </ng-template>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Operation/Operation.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AuthService from "../../services/auth.service";
import OperationService from "../../services/operation.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import { Modal, Button } from "react-bootstrap";

import Moment from "moment";

import {
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../services/local.service";

import { useParams } from "react-router-dom";

const Operation = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [ops, setOps] = useState([]);

  const [partHistory, setPartHistory] = useState({});
  const [isOpen, setIsOpen] = useState(false);
  const openModal = () => setIsOpen(true);
  const closeModal = () => setIsOpen(false);

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getAllWorkOrderOperations(id);
  }, []);

  const getAllWorkOrderOperations = (id) => {
    OperationService.getAllWorkOrderOperations(id)
      .then((response) => {
        console.log(response.data);
        setOps(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        }
      });
  };

  const displayDate = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return Moment(cell).format("DD-MMM-YYYY");
    }
  };

  const displayOpStatus = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return getOperationStatus(cell);
    }
  };

  const displayDetails = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return cell;
    }
  };

  const displayPKColumn = (cell, row) => {
    return (
      <span>
        <Button
          className="btn btn-primary"
          type="button"
          onClick={(e) => getOpLog(e, row.operationId)}
        >
          <i className="bi-binoculars"></i>
        </Button>
        &nbsp;{cell}
      </span>
    );
  };

  const displayActionBtn = (cell, row) => {
    // console.log(row);
    return (
      <div>
        {" "}
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editOp(e, row.operationId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>{" "}
        <Button
          className="btn btn-warning"
          type="button"
          onClick={(e) => xferParts(e, row.operationId)}
        >
          <i className="bi-arrows-move"></i>
        </Button>{" "}
        <Button
          className="btn btn-success"
          type="button"
          onClick={(e) => getPartHistory(e, row.operationId)}
        >
          <i className="bi-clock-history"></i>
        </Button>
      </div>
    );
  };
  const columns = [
    {
      dataField: "operationId",
      text: "OP #",
      formatter: (cell, row) => displayPKColumn(cell, row),
    },
    {
      dataField: "details",
      text: "Details",
      formatter: (cell) => displayDetails(cell),
    },
    {
      dataField: "operationStatus",
      text: "Status",
      formatter: (cell) => displayOpStatus(cell),
    },
    {
      dataField: "operationStartDate",
      text: "Start Date",
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "opQTYDone",
      text: "QTY-Done",
    },
    {
      dataField: "opQTYRequired",
      text: "QTY-Required",
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const getPartHistory = (e, opId) => {
    console.log("parts xfer history for op : ", opId);

    OperationService.getPartHistory(opId)
      .then((response) => {
        console.log(response.data);
        setPartHistory(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        } else if (e.response.status === 400)
          setPartHistory({ apiError: e.response.data });
      });

    openModal();
  };

  const xferParts = (e, opId) => {
    console.log("xfer parts to op : ", opId);
    navigate("/xfer-parts/" + opId);
  };

  const getOpLog = (e, opId) => {
    console.log("operation-log data for op : ", opId);
    navigate("/operation-log/" + opId);
  };

  const editOp = (e, opId) => {
    console.log("edit op : ", opId);
    navigate("/operation-edit", {
      state: {
        workOrderId: id,
        operationId: opId,
      },
    });
  };

  const createNewOp = () => {
    console.log("create new operation for wo# ", id);
    // navigate("/operation-create");

    navigate("/operation-create", {
      state: {
        workOrderId: id,
      },
    });
  };

  return (
    <div className="container">
      <div className="mainHeader">Work-Orders [Operations]</div>
      <hr />

      <div className="row">
        <div className="col-md-3 mx-auto">
          <Button
            className="btn btn-success"
            type="button"
            onClick={(e) => createNewOp(e)}
          >
            Create New Operation
          </Button>
        </div>
        <div className="col-md-6 mx-auto">
          <div className="subHeaderOp">Work-Order # {id}</div>
          {ops && ops.length > 0 && (
            <div className="subHeaderOp">Operations</div>
          )}
        </div>
        <div className="col-md-3 mx-auto"></div>
      </div>

      <p></p>

      {ops && ops.length > 0 ? (
        <BootstrapTable
          bootstrap4
          keyField="operationId"
          data={ops}
          columns={columns}
          pagination={paginationFactory({ sizePerPage: 20 })}
          filter={filterFactory()}
        />
      ) : (
        <div className="noOps">No Operations!</div>
      )}

      <p></p>
      <div className="container">
        <Modal show={isOpen} onHide={closeModal}>
          <Modal.Header closeButton>
            <Modal.Title>Parts XFER History</Modal.Title>
          </Modal.Header>
          {partHistory.apiError ? (
            <div className="apiErrorHistoryData">{partHistory.apiError}</div>
          ) : (
            <Modal.Body>
              <div className="card historyData">
                <div className="card-header">
                  Operation # {partHistory.operationId}
                </div>
                <div className="card-body">
                  Operation Number #{" "}
                  {getOperationNumber(partHistory.operationNumber)}
                  <br />
                  Work-Order # {partHistory.workOrderId}
                </div>
              </div>
            </Modal.Body>
          )}

          <Modal.Footer>
            <Button variant="secondary" onClick={closeModal}>
              Close
            </Button>
          </Modal.Footer>
        </Modal>
      </div>
    </div>
  );
};

export default Operation;
