// NgApp-WOT/src/app/part-edit/part-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-part-edit',
  templateUrl: './part-edit.component.html',
  styleUrls: ['./part-edit.component.css']
})
export class PartEditComponent implements OnInit {

  partId: string;

  partForm: FormGroup;
  submitted = false;
  partModel = { 
    partId: 0,
    name: '',
    desc: '',
    qty: 0
  };

  apiResponse = '';
  responseColor = '';
  
  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  ngOnInit(): void {
     this.partForm = this.fb.group({
      Name: ['', Validators.required],
      Desc: ['', Validators.required],
      Qty: ['', [Validators.required, Validators.pattern("^[0-9]*$")]]
     });
    
    this.partId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.partId)) {
      console.log('Not a Number!');
      this.router.navigate(['/part']);
    }
    else {
      this.dataService.getPart(Number(this.partId))
        .subscribe(
          data => {
            if(data==null){
              console.log('part not found!');
           
              this.apiResponse = 'Part Not Found!';
              this.responseColor = 'red';
            }
            else{
              this.apiResponse = '';
              this.responseColor = 'green';
       
              this.partForm.setValue({
                Name: data.name,
                Desc: data.desc,
                Qty: data.qty
              });
            }
          },
          error => {
            console.log(error);
            /*
            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
            */
          });
    }
  }

  get partFormControl() {
    return this.partForm.controls;
  }

  onSubmit(): void {
    this.submitted = true;
    if (this.partForm.valid) {
      
      this.partModel.name = this.partForm.value["Name"];
      this.partModel.desc = this.partForm.value["Desc"];
      this.partModel.qty = Number(this.partForm.value["Qty"]);
      this.partModel.partId = Number(this.partId);

      console.log(this.partModel);

      this.dataService.editPart(this.partModel)
        .subscribe(
          response => {

            if (response.responseCode == 0) {
              
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetPart();
              this.submitted = false;
              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/part']);
              }, 2000);  
            }
            else {
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
    }
  }
  
  resetPart(){
    this.partForm.reset();
    this.submitted = false;
  }

  checkForNumbersOnly(newVal) {
    /*
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal))
      console.log('ok');
    else
      console.log('Only Numbers Allowed !!!');
    */
  }
}

<div class="container">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-header componentHeader">    
                <h4>
                    <div>
                        #{{partId}}) Part - Edit
                    </div>                  
                </h4>
                <h5 *ngIf="apiResponse">
                    <span [style.color]="responseColor">
                        {{apiResponse}}
                    </span>
                </h5>
            </div>
            <div class="card-body">
                <form class="form-part" 
                    [formGroup]="partForm" 
                    (ngSubmit)="onSubmit()">
                    <div class="form-group">
                        <label>Part Name</label>
                        <input type="text" class="form-control nameField" formControlName="Name" />
                        <div class="alert alert-danger mt-2"
                            *ngIf="(partFormControl.Name.touched || submitted) && partFormControl.Name.errors?.required">
                            Part Name is required
                        </div>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <label>Part Desc</label>
                        <textarea type="text" class="form-control" formControlName="Desc">
                                                </textarea>
                        <div class="alert alert-danger mt-2"
                            *ngIf="(partFormControl.Desc.touched || submitted) && partFormControl.Desc.errors?.required">
                            Part Desc is required
                        </div>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <label>Initial Qty</label>
                        <input type="text" (ngModelChange)="checkForNumbersOnly($event)" class="form-control qtyField"
                            formControlName="Qty" />
                        <div class="alert alert-danger mt-2"
                            *ngIf="(partFormControl.Qty.touched || submitted) && partFormControl.Qty.errors?.required">
                            Initial Qty is required
                        </div>
                        <div class="alert alert-danger mt-2"
                            *ngIf="(partFormControl.Qty.touched || submitted) && partFormControl.Qty.errors?.pattern">
                            Only Numbers are allowed
                        </div>
                    
                    </div>
                    <p></p>
                    <hr />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" 
                                    class="btn btn-success">
                                    Edit Part
                                </button>
                            </div>
                            <div class="col-sm-6">
                                <button type="button" 
                                    (click)="resetPart()" 
                                    class="btn btn-primary cancelBtn">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Part_Edit/Part_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import PartService from "../../services/part.service";

import { useNavigate } from "react-router";

const Part_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [modelErrors, setModelErrors] = useState([]);

  const [partEditResponse, setPartEditResponse] = useState({});

  // form
  const [name, setName] = useState("");
  const [desc, setDesc] = useState("");
  const [qty, setQty] = useState(0);
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getPart(id);
  }, []);

  const getPart = (id) => {
    console.log("Editing Part : ", id);
    if (checkForNumbersOnly(id)) {
      PartService.getPart(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var partEditResponse = {
              responseCode: -1,
              responseMessage: "Part Not Found!",
            };

            setPartEditResponse(partEditResponse);
          } else {
            console.log(response.data);

            setName(response.data.name);
            setDesc(response.data.desc);
            setQty(parseInt(response.data.qty));
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/part");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleName = (event) => {
    setName(event.target.value);
    if (!errors[name])
      setErrors({
        ...errors,
        name: "",
      });
  };
  const handleDesc = (event) => {
    setDesc(event.target.value);
    if (!errors[desc])
      setErrors({
        ...errors,
        desc: "",
      });
  };
  const handleQty = (event) => {
    setQty(event.target.value);
    if (!errors[qty])
      setErrors({
        ...errors,
        qty: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};
    /*
    if (!name || name === "") newErrors.name = "Part Name is Required!";

    if (!desc || desc === "") newErrors.desc = "Part Desc is Required!";

    if (!qty || qty === "") newErrors.qty = "Qty is Required!";
    else {
      if (!checkForNumbersOnly(qty))
        newErrors.qty = "Only Numbers are Allowed!";
    }
    */
    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      // for (let prop in error.response.data.errors) {
      for (let prop in error.response.data) {
        if (error.response.data[prop].length > 1) {
          for (let error_ in error.response.data[prop]) {
            errors.push(error.response.data[prop][error_]);
          }
        } else {
          errors.push(error.response.data[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var partModel = {
        partId: parseInt(id),
        name: name,
        desc: desc,
        qty: parseInt(qty),
      };

      console.log(partModel);

      // api call
      PartService.editPart(partModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setPartEditResponse({});
          var partEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          setPartEditResponse(partEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              resetForm();
              navigate("/part");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setPartEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setName("");
    setDesc("");
    setQty(0);
    setPartEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-5 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Edit Part</h3>
                <p></p>{" "}
                {partEditResponse && partEditResponse.responseCode === -1 ? (
                  <span className="partEditError">
                    {partEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="partEditSuccess">
                    {partEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <Form.Group controlId="name">
                    <Form.Label>Name</Form.Label>
                    <Form.Control
                      value={name}
                      type="text"
                      isInvalid={!!errors.name}
                      onChange={(e) => handleName(e)}
                    />

                    <Form.Control.Feedback type="invalid">
                      {errors.name}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <Form.Group controlId="desc">
                    <Form.Label>Desc</Form.Label>
                    <Form.Control
                      value={desc}
                      as="textarea"
                      rows="3"
                      isInvalid={!!errors.desc}
                      onChange={(e) => handleDesc(e)}
                    />

                    <Form.Control.Feedback type="invalid">
                      {errors.desc}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <Form.Group controlId="qty">
                    <Form.Label>Qty</Form.Label>
                    <Form.Control
                      value={qty}
                      className="qtyDisplay"
                      type="text"
                      isInvalid={!!errors.qty}
                      onChange={(e) => handleQty(e)}
                    />

                    <Form.Control.Feedback type="invalid">
                      {errors.qty}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Part
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Part_Edit;
