// reactapp-wot/src/components/Customer_Order/Customer_Order.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AuthService from "../../services/auth.service";
import CustomerOrderService from "../../services/customerOrder.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Button from "react-bootstrap/Button";

import Moment from "moment";

const Customer_Order = () => {
  let navigate = useNavigate();

  const [cos, setCos] = useState([]);
  const getAllCustomerOrders = () => {
    CustomerOrderService.allCustomerOrders()
      .then((response) => {
        setCos(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        }
      });
  };

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getAllCustomerOrders();
  }, []);

  const displayDate = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return Moment(cell).format("DD-MMM-YYYY");
    }
  };

  const displayActionBtn = (cell, row) => {
    // console.log(row);
    return (
      <div>
        <Button
          className="btn btn-info"
          type="button"
          onClick={(e) => editCo(e, row.customerOrderId)}
        >
          <i className="bi bi-pencil-square"></i>
        </Button>
        <Button
          className="btn btn-danger"
          type="button"
          onClick={(e) => removeCo(e, row.customerOrderId)}
        >
          <i className="bi bi-trash"></i>
        </Button>
        <Button
          className="btn btn-warning"
          type="button"
          onClick={(e) => coProgressReport(e, row.customerOrderId)}
        >
          <i className="bi-arrow-repeat"></i>
        </Button>
      </div>
    );
  };
  const columns = [
    {
      dataField: "customerOrderId",
      text: "#",
      sort: true,
    },
    {
      dataField: "customerName",
      text: "Name",
      sort: true,
    },
    {
      dataField: "productName",
      text: "Product",
    },
    {
      dataField: "productDesc",
      text: "Pr-Desc",
    },
    {
      dataField: "orderQuantity",
      text: "Order-Qty",
    },
    {
      dataField: "orderDate",
      text: "Order-Date",
      sort: true,
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "orderDueDate",
      text: "Due-Date",
      sort: true,
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "actions",
      text: "Actions",
      formatter: (cell, row) => displayActionBtn(cell, row),
    },
  ];

  const createNewCo = () => {
    navigate("/customer-order-create");
  };
  const editCo = (e, coId) => {
    console.log("edit co : ", coId);
    navigate("/customer-order-edit/" + coId);
  };
  const removeCo = (e, coId) => {
    console.log("remove co : ", coId);
    navigate("/customer-order-remove/" + coId);
  };
  const coProgressReport = (e, coId) => {
    navigate("/customer-order-progress-text-report/" + coId);
  };

  return (
    <div className="container">
      <div className="mainHeader">Customer-Orders</div>
      <hr />
      <Button
        className="btn btn-success"
        type="button"
        onClick={(e) => createNewCo(e)}
      >
        Create New Customer-Order
      </Button>
      <p></p>
      {cos && cos.length > 0 ? (
        <BootstrapTable
          bootstrap4
          keyField="customerOrderId"
          data={cos}
          columns={columns}
          pagination={paginationFactory({ sizePerPage: 5 })}
          filter={filterFactory()}
        />
      ) : (
        <div className="noCos">No Customer-Orders!</div>
      )}
    </div>
  );
};

export default Customer_Order;

// NgApp-WOT/src/app/customer-order/customer-order.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-customer-order',
  templateUrl: './customer-order.component.html',
  styleUrls: ['./customer-order.component.css']
})
export class CustomerOrderComponent implements OnInit {

  term: string;
  
  cos: Array<any>;

  apiResponse = '';  
  responseColor = '';
  responseClass = '';
  
  page: number = 1;
  count: number = 0;
  tableSize: number = 3;
  tableSizes: any = [3, 6, 9, 12];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
    this.loadCos();  
  }

  onTableDataChange(event: any) {
    this.page = event;
    this.loadCos();
  }
  onTableSizeChange(event: any): void {
    this.tableSize = event.target.value;
    this.page = 1;
    this.loadCos();
  }

  loadCos(){
    this.dataService.allCustomerOrders()
      .subscribe(
        data => {          
          console.log(data);

          this.cos = data;
          this.responseColor = 'green';
          this.apiResponse = 'Success!';
          this.responseClass = 'successResponse';

          console.log(this.cos);
        },
        error => {
          console.log(error);
          if (error.status == 401)            
            this.apiResponse = 'Un-Authorized !';
          else
            this.apiResponse = 'Error !';
          
          this.responseColor = 'red';
          this.responseClass = 'errorResponse';
          this.cos = [];      
      });
  }

  editCo(co) {
    this.router.navigate(['/customer-order-edit/'+ co.customerOrderId]);
  }

  removeCo(co) {
    this.router.navigate(['/customer-order-remove/'+ co.customerOrderId]);
  }

  coProgressReport(co) {
    this.router.navigate(['/customer-order-progress-text-report/'+ co.customerOrderId]);
  }
  
  createCo() {
    console.log('new customer-order!');
    setTimeout(() => {
      this.router.navigate(['/customer-order-create']);
    }, 500);
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header componentHeader">
                    <h4>
                        Customer-Orders
                        <p></p>
                        <span *ngIf="responseColor=='red'" 
                            [class]="responseClass">
                            {{apiResponse}}
                        </span>
                    </h4>

                    <p></p>
                    <div>
                        <button type="button" 
                            (click)="createCo()" 
                            class="btn btn-success">
                            Create New Customer-Order
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div 
                        *ngIf="cos?.length>0; else noCos" 
                        class="container">

                        <div class="form-group">
                            <input type="text" 
                                class="searchControl form-control" 
                                placeholder="Search Customer-Order"
                                [(ngModel)]="term">
                        </div>
                        <p></p>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Product</th>
                                    <th>Pr-Desc</th>
                                    <th>Order-Qty</th>
                                    <th>Order-Date</th>
                                    <th>Due-Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let co of cos  | filter:term | paginate
                                        : {
                                            itemsPerPage: tableSize,
                                            currentPage: page,
                                            totalItems: count
                                        };
                                        let i = index
                                    ">
                                    <th scope="row">{{ co.customerOrderId }}</th>
                                    <td>{{ co.customerName }}</td>
                                    <td>{{ co.productName }}</td>
                                    <td>
                                        <span *ngIf="co.productDesc!=null && co.productDesc.length>10; else fullDesc">
                                            {{co.productDesc.substring(0,10)}}...
                                        </span>
                                        <ng-template #fullDesc>
                                            {{co.productDesc}}
                                        </ng-template>
                                    </td>
                                    <td>{{ co.orderQuantity }}</td>
                                    <td>
                                        {{ co.orderDate | date: "dd-MMM,yyyy" }}
                                    </td>
                                    <td>
                                        {{ co.orderDueDate | date: "dd-MMM,yyyy" }}
                                    </td>
                                    <td>
                                        <div class="row">
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="editCo(co)" 
                                                    class="btn btn-primary">
                                                    <i class="bi bi-pencil-square"></i>
                                                </button>
                                            </div>
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="removeCo(co)" 
                                                    class="btn btn-danger">
                                                    <i class="bi bi-trash"></i>
                                                </button>
                                            </div>  
                                            <div class="col-1"></div>
                                            <div class="col-1">
                                                <button type="button" 
                                                    (click)="coProgressReport(co)" 
                                                    class="btn btn-success">
                                                    <i class="bi-arrow-repeat"></i>
                                                </button>
                                            </div>
                                            <div class="col-6"></div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                            <pagination-controls previousLabel="Prev" nextLabel="Next"
                                (pageChange)="onTableDataChange($event)">
                            </pagination-controls>
                        </div>
                    </div>
                    <ng-template #noCos>
                        <div class="container">
                            <span class="noCos">
                                Customer-Orders Not Found !
                            </span>
                        </div>
                    </ng-template>
                </div>
            </div>
        </div>
    </div>
</div>
