// NgApp-WOT/src/app/part-create/part-create.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { DataService } from '../services/data.service';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-part-create',
  templateUrl: './part-create.component.html',
  styleUrls: ['./part-create.component.css']
})
export class PartCreateComponent implements OnInit {

  partForm: FormGroup;
  submitted = false;
  partModel = {
    name: '',
    desc: '',
    qty: 0
  };

  apiResponse = '';  
  responseColor = '';

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  ngOnInit(): void {
    this.partForm = this.fb.group({
      Name: ['', Validators.required],
      Desc: ['', Validators.required],
      Qty: ['', [Validators.required, Validators.pattern("^[0-9]*$")]]
    });
  }

  get partFormControl() {
    return this.partForm.controls;
  }
  onSubmit(): void {
    this.submitted = true;

    if (this.partForm.valid) {
      this.partModel.name = this.partForm.value["Name"];
      this.partModel.desc = this.partForm.value["Desc"];
      this.partModel.qty = Number(this.partForm.value["Qty"]);

      this.dataService.createPart(this.partModel)
        .subscribe(
          response => {
            console.log(response);

            if(response.responseCode==0){
              // success    
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.resetPart();
              this.submitted = false;

              
              setTimeout(() => {
                this.apiResponse = ''; 
                this.router.navigate(['/part']);
              }, 2000);  
              
            }
            else{
              // -1
              // server error
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
            }
          },
          error => {
            console.log(error);

            if (error.status == 401)            
              this.apiResponse = 'Un-Authorized !';
            else
              this.apiResponse = 'Error !';
            
            this.responseColor = 'red';
          }
        );
    }
  } 

  resetPart() {    
    this.partForm.reset();
    this.submitted = false;
  }

  checkForNumbersOnly(newVal) {
    /*
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal))
      console.log('ok');
    else
      console.log('Only Numbers Allowed !!!');
    */
  }
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-header componentHeader" >
                    <h4>
                        <div>
                            Create New Part
                        </div>                     
                    </h4>
                    <h5 *ngIf="apiResponse">
                        <p></p>
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                    </h5>
                </div>

                <div class="card-body">
                    <form 
                        class="form-part" 
                        [formGroup]="partForm" 
                        (ngSubmit)="onSubmit()">
                        <div class="form-group">
                            <label>Part Name</label>
                            <input type="text" 
                                class="form-control nameField" 
                                formControlName="Name" />
                            <div class="alert alert-danger mt-2"
                                *ngIf="(partFormControl.Name.touched || submitted) && partFormControl.Name.errors?.required">
                                Part Name is required
                            </div>
                        </div>
                        <p></p>
                        <div class="form-group">
                            <label>Part Desc</label>
                            <textarea type="text" 
                                class="form-control" 
                                formControlName="Desc" >
                            </textarea>
                            <div class="alert alert-danger mt-2"
                                *ngIf="(partFormControl.Desc.touched || submitted) && partFormControl.Desc.errors?.required">
                                Part Desc is required
                            </div>
                        </div>
                        <p></p>
                        <div class="form-group">
                            <label>Initial Qty</label>
                            <input type="text" 
                                (ngModelChange)="checkForNumbersOnly($event)"
                                class="form-control qtyField" 
                                formControlName="Qty" />
                            <div class="alert alert-danger mt-2"
                                *ngIf="(partFormControl.Qty.touched || submitted) && partFormControl.Qty.errors?.required">
                                Initial Qty is required
                            </div>
                            <div class="alert alert-danger mt-2"
                                *ngIf="(partFormControl.Qty.touched || submitted) && partFormControl.Qty.errors?.pattern">
                                Only Numbers are allowed
                            </div>
                          
                        </div>
                        <p></p>
                        <hr />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <button type="submit" 
                                        class="btn btn-success">
                                        New Part
                                    </button>
                                </div>
                                <div class="col-sm-4"></div>
                                <div class="col-sm-4 ">
                                    <button type="button" 
                                        (click)="resetPart()" 
                                        class="btn btn-primary cancelBtn">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

// reactapp-wot/src/components/Part_Create/Part_Create.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import PartService from "../../services/part.service";

import { useNavigate } from "react-router";

const Part_Create = () => {
  let navigate = useNavigate();

  const [modelErrors, setModelErrors] = useState([]);

  const [partCreateResponse, setPartCreateResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
  }, []);

  // reset form
  // form reference
  const formRef = useRef(null);

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const { name, desc, qty } = form;
    const newErrors = {};

    if (!name || name === "") newErrors.name = "Part Name is Required!";

    if (!desc || desc === "") newErrors.desc = "Part Desc is Required!";

    if (!qty || qty === "") newErrors.qty = "Qty is Required!";
    else {
      if (!checkForNumbersOnly(qty))
        newErrors.qty = "Only Numbers are Allowed!";
    }

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var partModel = {
        name: form.name,
        desc: form.desc,
        qty: parseInt(form.qty),
      };

      console.log(partModel);

      // api call
      PartService.createPart(partModel)
        .then((response) => {
          setModelErrors([]);
          setPartCreateResponse({});
          console.log(response.data);
          var partCreateResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };
          if (response.data.responseCode === 0) {
            resetForm();
            setPartCreateResponse(partCreateResponse);

            setTimeout(() => {
              navigate("/part");
            }, 3000);
          } else if (response.data.responseCode === -1) {
            setPartCreateResponse(partCreateResponse);
          }
        })
        .catch((error) => {
          console.log(error);
          setModelErrors([]);
          setPartCreateResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setPartCreateResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-5 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>Create New Part</h3>
                <p></p>{" "}
                {partCreateResponse &&
                partCreateResponse.responseCode === -1 ? (
                  <span className="partCreateError">
                    {partCreateResponse.responseMessage}
                  </span>
                ) : (
                  <span className="partCreateSuccess">
                    {partCreateResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <Form.Group controlId="name">
                    <Form.Label>Name</Form.Label>
                    <Form.Control
                      type="text"
                      isInvalid={!!errors.name}
                      onChange={(e) => setField("name", e.target.value)}
                    />
                    <Form.Control.Feedback type="invalid">
                      {errors.name}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <Form.Group controlId="desc">
                    <Form.Label>Desc</Form.Label>
                    <Form.Control
                      as="textarea"
                      rows="3"
                      isInvalid={!!errors.desc}
                      onChange={(e) => setField("desc", e.target.value)}
                    />
                    <Form.Control.Feedback type="invalid">
                      {errors.desc}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <Form.Group controlId="qty">
                    <Form.Label>Qty</Form.Label>
                    <Form.Control
                      className="qtyDisplay"
                      type="text"
                      isInvalid={!!errors.qty}
                      onChange={(e) => setField("qty", e.target.value)}
                    />
                    <Form.Control.Feedback type="invalid">
                      {errors.qty}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Create Part
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Part_Create;
