// NgApp-WOT/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LocalDataService } from '../services/local-data.service';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  public isUserAuthenticated: boolean;
  
    constructor(public localDataService: LocalDataService, public userService: UserService, private _router: Router) {
    this.userService.authChanged
      .subscribe(res => {
        this.isUserAuthenticated = res;
      })
  }

  ngOnInit(): void {   
    this.localDataService.setUserName(localStorage.getItem('userName')); 
    this.localDataService.setFullName(localStorage.getItem('fullName')); 
    this.localDataService.setMyRole(localStorage.getItem('myRole'));
  }

  logout() {
    this.userService.doLogout();   
  }

}

<nav class="navbar navbar-expand-xl navbar-light bg-warning">   
    <div class="container-fluid">
        <a 
            *ngIf="this.userService.isLoggedIn && this.userService.isAdmin"     
            class="navbar-brand" href="#">
            <b>
                WorkOrder-Tracking
                <label class="adminHeader">
                    [{{this.localDataService.getMyRole()}}]
                </label>
            </b>
        </a>
        <a *ngIf="this.userService.isLoggedIn && !this.userService.isAdmin" class="navbar-brand" href="#">
            <b>
                WorkOrder-Tracking
                <label class="operatorHeader">
                    [{{this.localDataService.getMyRole()}}]
                </label>
            </b>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ngx-navbar-collapse id="navbarSupportedContent">
            <b>
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class='nav-link' aria-current="page" 
                            [routerLink]="['/home']">
                            <i class="bi bi-house-fill"></i>
                            Home                            
                        </a>
                    </li>
                    <li class="nav-item"
                        *ngIf="this.userService.isLoggedIn && this.userService.isAdmin" >
                        <a class="nav-link" 
                            [routerLink]="['/part']">
                            <i class="bi bi-display"></i>
                            Parts
                        </a>
                    </li>
                    <li class="nav-item"
                        *ngIf="this.userService.isLoggedIn && this.userService.isAdmin" >
                        <a class="nav-link" 
                            [routerLink]="['/customer-order']">
                            <i class="bi-gear-fill"></i>
                            Customer-Orders
                        </a>
                    </li>
                    <li class="nav-item" 
                        *ngIf="this.userService.isLoggedIn && this.userService.isAdmin">
                        <a class="nav-link" 
                            [routerLink]="['/work-order']">
                            <i class="bi-file-word-fill"></i>
                            Work-Orders [Operations]
                            <i class="bi-hourglass-top"></i>
                        </a>
                    </li>

                    <li class="nav-item" 
                        *ngIf="this.userService.isLoggedIn && !this.userService.isAdmin">
                        <a class="nav-link" 
                            [routerLink]="['/create-op-log']">
                            Create Log
                        </a>
                    </li>
                    <li class="nav-item"
                        *ngIf="this.userService.isLoggedIn && !this.userService.isAdmin">
                        <a class="nav-link" 
                            [routerLink]="['/view-op-log']">
                            View Log
                        </a>
                    </li>
                </ul>
            </b>

            <ul class="navbar-nav ms-auto ">
                <li class="nav-item" *ngIf="!this.userService.isLoggedIn">
                    <a class='nav-link' [routerLink]="['/signin']">
                        <i class="bi bi-person-plus"></i>
                        Login
                    </a>
                </li>
                <li class="nav-item" *ngIf="!this.userService.isLoggedIn">
                    <a class='nav-link' [routerLink]="['/registration']">
                        <i class="bi bi-person-square"></i>
                        Registration
                    </a>
                </li>
                <label class="adminUser" *ngIf="this.userService.isLoggedIn && this.userService.isAdmin">
                    <b>
                        Welcome...{{this.localDataService.getFullName()}} !
                    </b>
                </label>
                <label class="operatorUser" *ngIf="this.userService.isLoggedIn && !this.userService.isAdmin">
                    <b>
                        Welcome...{{this.localDataService.getFullName()}} !
                    </b>
                </label>
                <button (click)="logout()" *ngIf="this.userService.isLoggedIn" type="button" class="btn btn-danger">
                    Logout
                </button>
            </ul>

        </ngx-navbar-collapse>


        <!-- 
        <ngx-navbar-collapse id="navbarSupportedContent">
            <b>
               
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"
                        *ngIf="!this.userService.isLoggedIn" >
                        <a class='nav-link' 
                            [routerLink]="['/signin']">
                            <i class="bi bi-person-plus"></i>
                            Login
                        </a>
                    </li>
                    <li class="nav-item" 
                        *ngIf="!this.userService.isLoggedIn" >
                        <a class='nav-link' 
                            [routerLink]="['/registration']">
                            <i class="bi bi-person-square"></i>
                            Registration
                        </a>
                    </li>    
                    <label 
                        class="adminUser"
                        *ngIf="this.userService.isLoggedIn && this.userService.isAdmin">
                        <b>
                            Welcome...{{this.localDataService.getFullName()}} !
                        </b>
                    </label>
                    <label 
                        class="operatorUser"
                        *ngIf="this.userService.isLoggedIn && !this.userService.isAdmin">
                        <b>
                            Welcome...{{this.localDataService.getFullName()}} !
                        </b>
                    </label>
                    <button 
                        (click)="logout()" 
                        *ngIf="this.userService.isLoggedIn" 
                        type="button" 
                        class="btn btn-danger">
                            Logout
                    </button>
                </ul>


              

            </b>
        </ngx-navbar-collapse>
        -->

     
     

    </div>
</nav>

// reactapp-wot/src/components/Header/Header.jsx
import React from "react";
import {
  BrowserRouter as Router,
  useParams,
} from "react-router-dom";
import { Routes, Route, Link } from "react-router-dom";
import { Navbar, Container, NavDropdown, Nav, Dropdown } from "react-bootstrap";

import Home from "../Home/Home";
import Login from "../Login/Login";
import Register from "../Registration/Register";
import NotFound from "../NotFound/NotFound";
import Part from "../Part/Part";

import "./style.css";

class Header extends React.Component {
  render() {
      return (
        <>
          <Navbar            
            variant="light"
            expand="lg"
            sticky="top"
            className="navBar"
          >
            <Container>
              <Navbar.Brand href="#home">WorkOrder-Tracking</Navbar.Brand>
              <Navbar.Toggle aria-controls="basic-navbar-nav" />
              <Navbar.Collapse id="basic-navbar-nav">
                <Nav className="mr-auto">
                  <Link to={"/home"} className="nav-link">
                    <i className="bi bi-house-fill"></i>
                    Home
                  </Link>
                  <Link to={"/part"} className="nav-link">
                    <i className="bi bi-display"></i>
                    Part
                  </Link>
                  <Link to={"/customer-order"} className="nav-link">
                    <i className="bi-gear-fill"></i>
                    Customer-Order
                  </Link>
                  <Link to={"/work-order"} className="nav-link">
                    <i className="bi-file-word-fill"></i>
                    Work-Orders [Operations]
                    <i className="bi-hourglass-top"></i>
                  </Link>
                  <Link to={"/create-operator-log"} className="nav-link">
                    Create Log
                  </Link>
                </Nav>

                <Nav className="navbar-nav ms-auto">
                  <Link to={"/login"} className="nav-link">
                    <i className="bi bi-person-plus"></i>
                    Login
                  </Link>
                  <Link to={"/register"} className="nav-link">
                    <i className="bi bi-person-square"></i>
                    Register
                  </Link>
                </Nav>
              </Navbar.Collapse>
            </Container>
          </Navbar>
        </>
      );
  }
}
export default Header;
