// NgApp-WOT/src/app/xfer-history/xfer-history.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import {NgbModal, ModalDismissReasons} from '@ng-bootstrap/ng-bootstrap';

import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-xfer-history',
  templateUrl: './xfer-history.component.html',
  styleUrls: ['./xfer-history.component.css']
})
export class XferHistoryComponent implements OnInit {

  @Input() partHistoryData;
  @Input() apiError;

  // partHistoryData.partList
  partList = [];

  page: number = 1;
  count: number = 0;
  tableSize: number = 2;
  tableSizes: any = [3, 6, 9, 12];

  constructor(private activeModal: NgbActiveModal, public localDataService: LocalDataService,) {}

  ngOnInit(): void {
    this.loadPartXferData();  
  }

  onTableDataChange(event: any) {
    this.page = event;
    this.loadPartXferData();
  }
  onTableSizeChange(event: any): void {
    this.tableSize = event.target.value;
    this.page = 1;
    this.loadPartXferData();
  }

  loadPartXferData() {
    this.partList = this.partHistoryData.partList;
  }

  closeModal() {
    this.activeModal.close('Modal Closed');
  }


}

<div class="modal-header">
    <h4 class="modal-title">Parts XFER History</h4>
</div>
<div class="modal-body">
    <div *ngIf="!apiError; else showApiError" class="card">
        <div class="card-header historyHeader">
            <div>
                Operation # {{partHistoryData.operationId}}
                <br />
                Operation Number #&nbsp;
                {{localDataService.getOperationNumber(partHistoryData.operationNumber)}}
                <br />
                Work-Order # {{partHistoryData.workOrderId}}
                <p></p>
            </div>
        </div>
        <div class="card-body">
            <div *ngIf="partList?.length>0; else noHistoryData" 
                class="historyData">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Part #</th>
                            <th>Name</th>
                            <th>XFER-QTY</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let d of partList | paginate
                                                        : {
                                                            itemsPerPage: tableSize,
                                                            currentPage: page,
                                                            totalItems: count
                                                        };
                                                        let i = index
                                                    ">
                            <th scope="row">{{ d.partId }}</th>
                            <td>{{d.partName}}</td>
                            <td>{{d.xferqty}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    <pagination-controls previousLabel="Prev" nextLabel="Next" (pageChange)="onTableDataChange($event)">
                    </pagination-controls>
                </div>


            </div>
            <ng-template #noHistoryData>
                <div class="noHistory">
                    No Parts XFER History!
                </div>
            </ng-template>
        </div>
    </div>
    <ng-template #showApiError>
        <div class="apiErrorHistoryData">
            {{apiError}}
        </div>
    </ng-template>
  
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-outline-dark" (click)="closeModal()">Close</button>
</div>

// reactapp-wot/src/components/Operation/Xfer_History/Xfer_History.jsx
import React, { useState, useEffect } from "react";
import "./style.css";
import AuthService from "../../../services/auth.service";
import OperationService from "../../../services/operation.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import { Modal, Button } from "react-bootstrap";

import Moment from "moment";

import {
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../../services/local.service";

import { useParams } from "react-router-dom";
const Xfer_History = ({ opId }) => {
  let navigate = useNavigate();

  const [partHistory, setPartHistory] = useState({});
  const [isOpen, setIsOpen] = useState(false);
  const openModal = () => {
    setIsOpen(true);
  };
  const closeModal = () => {
    setIsOpen(false);
  };

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      getPartHistory(opId);
    }
  }, [opId]);

  const getPartHistory = (opId) => {
    console.log("parts xfer history for op : ", opId);

    OperationService.getPartHistory(opId)
      .then((response) => {
        console.log(response.data);
        setPartHistory(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        } else if (e.response.status === 400)
          setPartHistory({ apiError: e.response.data });
      });

    openModal();
  };

  const columns = [
    {
      dataField: "partId",
      text: "Part #",
    },
    {
      dataField: "partName",
      text: "Name",
    },
    {
      dataField: "xferqty",
      text: "XFER-QTY",
    },
  ];

  return (
    <div className="container">
      <Modal show={isOpen} onHide={closeModal}>
        <Modal.Header closeButton>
          <Modal.Title>Parts XFER History</Modal.Title>
        </Modal.Header>
        {partHistory.apiError ? (
          <div className="apiErrorHistoryData">{partHistory.apiError}</div>
        ) : (
          <Modal.Body>
            <div className="card historyData">
              <div className="card-header">
                Operation # {partHistory.operationId}
              </div>
              <div className="card-body">
                Operation Number #{" "}
                {getOperationNumber(partHistory.operationNumber)}
                <br />
                Work-Order # {partHistory.workOrderId}
                <p></p>
                <div>
                  {partHistory.partList && partHistory.partList.length > 0 ? (
                    <BootstrapTable
                      bootstrap4
                      keyField="partId"
                      data={partHistory.partList}
                      columns={columns}
                      pagination={paginationFactory({ sizePerPage: 20 })}
                      filter={filterFactory()}
                    />
                  ) : (
                    <div className="noHistory">No Parts XFER History!</div>
                  )}
                </div>
              </div>
            </div>
          </Modal.Body>
        )}

        <Modal.Footer>
          <Button variant="secondary" onClick={closeModal}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default Xfer_History;
