// reactapp-wot/src/components/View_Operator_Log/View_Operator_Log.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import OperatorLogService from "../../services/operatorLog.service";
import {
  getViewMyLogDataEnumValues,
  getWorkOrderStatus,
  getDaysLeft,
  getOperationStatus,
  getOperationNumber,
  getOperationStatusForOperator,
} from "../../services/local.service";

import { useNavigate } from "react-router";
import { useLocation } from "react-router-dom";

import Moment from "moment";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

const View_Operator_Log = () => {
  let navigate = useNavigate();
  let location = useLocation();

  const [logData, setLogData] = useState([]);

  const [logDataOptions, setLogDataOptions] = useState([]);

  const [apiResponse, setApiResponse] = useState("");
  const [apiError, setApiError] = useState(false);
  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Operator"))
      navigate("/un-auth");
    else {
      setLogDataOptions(getViewMyLogDataEnumValues());
    }
  }, []);

  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const findFormErrors = () => {
    const { viewMyLogData } = form;
    const newErrors = {};

    if (!viewMyLogData || viewMyLogData === "")
      newErrors.viewMyLogData = "Log Option is required!";

    return newErrors;
  };

  const renderOptionsForViewMyLogData = () => {
    return logDataOptions.map((dt, i) => {
      return (
        <option value={dt.value} key={i} name={dt.text}>
          {dt.text}
        </option>
      );
    });
  };

  const displayDate = (cell) => {
    if (cell === null || cell === "") return "N/A";
    else {
      return Moment(cell).format("DD-MMM hh:mm A");
    }
  };

  const displayOperation = (cell, row) => {
    return (
      <span>
        <span># {cell}</span>
        <br />
        <span>{getOperationNumber(row.operationNumber)}</span>
        <br />
        <span>{getOperationStatus(row.operationStatus)}</span>
      </span>
    );
  };
  const columns = [
    {
      dataField: "operatorActivityId",
      text: "#",
    },
    {
      dataField: "workOrderId",
      text: "Wo #",
    },
    {
      dataField: "operationId",
      text: "Operation",
      formatter: (cell, row) => displayOperation(cell, row),
    },
    {
      dataField: "opStartRunTime",
      text: "Start Time",
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "opPauseRunTime",
      text: "Pause Time",
      formatter: (cell) => displayDate(cell),
    },
    {
      dataField: "cycleTime",
      text: "Cycle Time",
    },
    {
      dataField: "opQtyDone",
      text: "QTY Done",
    },
  ];

  const goBack = (e) => {
    navigate("/home");
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      console.log("form is valid!");

      var operatorLogDataView = {
        logDataRange: form.viewMyLogData,
        userId: AuthService.getCurrentUserId(),
      };
      console.log(operatorLogDataView);
      // api call
      OperatorLogService.getMyLogData(operatorLogDataView)
        .then((response) => {
          console.log(response.data);
          if (response.data.response.responseCode === 0) {
            setApiResponse(response.data.response.responseMessage);
            setApiError(false);
            setLogData(response.data.logData);
          } else {
            setApiResponse(
              response.data.response.responseCode +
                " : " +
                response.data.response.responseMessage
            );
            setApiError(true);
            setLogData([]);
          }
        })
        .catch((error) => {
          console.log(error);
          setApiResponse("Error !");
          setApiError(true);
          setLogData([]);
        });
    }
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div className="card-header">
                <div className="row">
                  <div className="col-md-10 mx-auto">
                    <h3>View Operator-Log</h3>
                    <p></p>
                  </div>
                  <div className="col-md-2 mx-auto">
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => goBack(e)}
                    >
                      <i className="bi bi-arrow-return-left"></i> Back
                    </Button>
                  </div>
                </div>
              </div>
              <div className="card-body">
                <Form>
                  <Form.Group controlId="viewMyLogData">
                    <Form.Control
                      className="displayOptions"
                      as="select"
                      isInvalid={!!errors.viewMyLogData}
                      onChange={(e) => {
                        setField("viewMyLogData", e.target.value);
                      }}
                    >
                      <option value="">Choose My Log Option</option>
                      {renderOptionsForViewMyLogData()}
                    </Form.Control>
                    <Form.Control.Feedback
                      className="formControlError"
                      type="invalid"
                    >
                      {errors.viewMyLogData}
                    </Form.Control.Feedback>
                  </Form.Group>
                  <p></p>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                    }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      View My Log
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>

        <p></p>
        <div className="row">
          <div className="col-md-12 mx-auto">
            <div>
              {logData && logData.length > 0 ? (
                <BootstrapTable
                  bootstrap4
                  keyField="operatorActivityId"
                  data={logData}
                  columns={columns}
                  pagination={paginationFactory({ sizePerPage: 10 })}
                  filter={filterFactory()}
                />
              ) : (
                <div>
                  {console.log(apiResponse)}
                  {apiResponse === "" ? (
                    <div></div>
                  ) : (
                    <div className="noData">Data Not Found!</div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default View_Operator_Log;

// NgApp-WOT/src/app/view-operator-log/view-operator-log.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LocalDataService } from '../services/local-data.service';
import { UserService } from '../services/user.service';
import { DataService } from '../services/data.service';

@Component({
  selector: 'app-view-operator-log',
  templateUrl: './view-operator-log.component.html',
  styleUrls: ['./view-operator-log.component.css']
})
export class ViewOperatorLogComponent implements OnInit {

  logData: Array<any>;

  viewMyLogDataEnumCollection: Array<any>;

  oprLogForm: FormGroup;
  submitted = false;
  oprLogModel = {
    logDataRange: 0,  
    userId: '',
  };
  
  apiResponse = '';  
  apiError = false;
  
  constructor(private formBuilder: FormBuilder,
    public userService: UserService,
    public router: Router,
    public localDataService: LocalDataService,
    public dataService: DataService,
    private fb: FormBuilder,) { }
  
  ngOnInit(): void {
    this.oprLogForm = this.fb.group({
      ViewMyLogData: ['', Validators.required],  
    });  
    this.viewMyLogDataEnumCollection = this.localDataService.getViewMyLogDataEnumValues();
  }

  get oprLogFormControl() {
    return this.oprLogForm.controls;
  }
  
  onSubmit(): void {

    this.apiResponse = '';
    this.apiError = false;
    this.logData = [];

    this.submitted = true;
    
    if (this.oprLogForm.valid) {      

      this.oprLogModel.logDataRange = this.oprLogForm.value["ViewMyLogData"]; 
      this.oprLogModel.userId = this.localDataService.getMyUserId();

      console.log(this.oprLogModel);
      
      this.dataService.getMyLogData(this.oprLogModel)
        .subscribe(
          response => {
            console.log(response);

            if(response.response.responseCode===0){
              // success    
              this.apiResponse = response.response.responseMessage;
              this.apiError = false;
              this.logData = response.logData;
            }
            else{
              // -1
              // server error
              this.apiResponse = response.response.responseCode + ' : ' + response.response.responseMessage;
              this.apiError = true;
              this.logData = [];
            }
          },
          error => {
            this.apiResponse = "Error !";
            this.apiError = true;
            this.logData = [];
          }
        );
    }
    else {
      console.log('form in-valid!');
    }    
  } 
}

<div>
    <div class="row">
        <div class="col-md-3 mx-auto">
            <div class="card">
                <div class="card-header componentHeader">
                    <form class="form-oprLog" 
                        [formGroup]="oprLogForm" 
                        (ngSubmit)="onSubmit()">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <select class="form-control" formControlName="ViewMyLogData">
                                        <option value="">Choose My Log Option</option>
                                        <option value={{log.value}} *ngFor="let log of viewMyLogDataEnumCollection">
                                            {{log.text}}
                                        </option>
                                    </select>                                     
                                    <div class="alert alert-danger mt-2"
                                        *ngIf="(oprLogFormControl.ViewMyLogData.touched || submitted) && oprLogFormControl.ViewMyLogData.errors?.required">
                                        Log Option is required
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-2"></div>
                        </div>
                    
                        <hr />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <button type="submit" 
                                        class="btn btn-success">
                                        View My Log
                                    </button>
                                </div>                               
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
        <div class="col-md-9 mx-auto">
            <div *ngIf="!apiError; else displayError">
                <div class="apiSuccess">
                    <div *ngIf="(logData?.length>0); else noData">
                        
                           <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Wo #</th>
                                    <th>Operation</th>
                                    <th>Start Time</th>
                                    <th>Pause Time</th>
                                    <th>Cycle Time</th>
                                    <th>QTY Done</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let co of logData 
                                        let i = index
                                    ">
                                    <th scope="row">{{ co.operatorActivityId }}</th>
                                    <td>{{ co.workOrderId }}</td>
                                    <td>
                                        <span>
                                            # {{co.operationId}}                                            
                                        </span>
                                        <br />
                                        <span>
                                            {{ localDataService.getOperationNumber(co.operationNumber)}}
                                        </span>
                                        <br />
                                        <span>
                                            {{ localDataService.getOperationStatusForOperator(co.operationStatus)}}
                                        </span>
                                    </td>
                                    <td>{{ co.opStartRunTime | date: "dd-MMM hh:mm a" }}</td>
                                    <td>{{ co.opPauseRunTime | date: "dd-MMM hh:mm a" }}</td>
                                    <td>{{ co.cycleTime }}</td>
                                    <td>{{ co.opQtyDone }}</td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <ng-template #noData>
                        <div *ngIf="apiResponse" class="container">
                            <span class="noData">
                                Data Not Found!
                            </span>
                        </div>
                    </ng-template>
                </div>   
            </div>
            <ng-template #displayError>
                <div class="container">
                    <span class="apiError">
                        {{apiResponse}}
                    </span>
                </div>
            </ng-template>
        </div>
    </div>
</div>
